"""Experimental AMBIA adapter for QDF1-style registration."""

from __future__ import annotations

from dataclasses import dataclass, field
import importlib.util
import json
import logging
import math
import os
from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
from scipy import ndimage as ndi
from skimage import feature, filters, measure, transform
import tifffile

from deepslice.pipeline import (
    ConvertedJpg,
    convert_tiffs_to_jpgs,
    discover_channel_tiffs,
    extract_section_id,
    load_ap_position_hints,
    sanitize_payload_for_quicknii,
    write_prediction_bundle,
)

LOG = logging.getLogger(__name__)

QDF1_MOUSE_TARGET = "ABA_Mouse_CCFv3_2017_25um.cutlas"
QDF1_MOUSE_TARGET_RESOLUTION = (456, 528, 320)
QDF1_MOUSE_VOXEL_SIZE_UM = 25.0
QDF1_MOUSE_BREGMA_X_UM = 5400.0
AMBIA_ATLAS_SLICE_MIN = 1
AMBIA_ATLAS_SLICE_MAX = 132
AMBIA_ATLAS_STEP_MM = 0.1
AMBIA_MATCH_SIZE = 256


@dataclass(slots=True)
class AmbiaAtlasTemplate:
    """One AMBIA atlas image prepared for shape matching."""

    atlas_num: int
    image_path: Path
    mask: np.ndarray
    signature: np.ndarray
    bbox: tuple[int, int, int, int]
    shape: tuple[int, int]


@dataclass(slots=True)
class AmbiaSliceMatch:
    """Registration estimate for one section."""

    converted: ConvertedJpg
    atlas_num: int
    score: float
    anchoring: list[float]
    source_bbox: tuple[int, int, int, int]
    atlas_bbox: tuple[int, int, int, int]
    top_candidates: list[tuple[int, float]]
    ap_mm: float
    qc_overlay_path: Path | None = None


@dataclass(slots=True)
class AlternativeRegistrationResult:
    """Artifacts generated by one alternative-registration adapter run."""

    method: str
    input_dir: Path
    output_dir: Path
    jpg_dir: Path
    status_path: Path
    report_path: Path
    qdf_json_path: Path | None = None
    converted_images: list[ConvertedJpg] = field(default_factory=list)
    status: str = "ok"


def run_ambia_adapter(
    input_dir: Path,
    channel: str,
    *,
    output_dir: Path | None = None,
    secondary_channel: str | None = None,
    ambia_root: Path | None = None,
    ap_hint_path: Path | None = None,
    enforce_ap_order: bool = True,
    progress_callback: Callable[[str, float], None] | None = None,
    logger: logging.Logger | None = None,
) -> AlternativeRegistrationResult:
    """Run AMBIA-style atlas matching and write a QDF1-compatible JSON."""

    logger = logger or LOG
    input_dir = Path(input_dir).resolve()
    output_dir = (Path(output_dir) if output_dir else input_dir.parent / "qdf1_ambia").resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    jpg_dir = output_dir / "jpg"
    jpg_dir.mkdir(parents=True, exist_ok=True)

    if progress_callback:
        progress_callback("Preparing AMBIA/QDF1 JPEGs", 0.20)
    converted = _prepare_qdf_jpegs(input_dir, channel, jpg_dir, logger=logger)
    if secondary_channel and secondary_channel.strip():
        _prepare_qdf_jpegs(input_dir, secondary_channel.strip().upper(), jpg_dir, logger=logger)

    if progress_callback:
        progress_callback("Loading AMBIA atlas templates", 0.38)
    ambia_root = _resolve_ambia_root(ambia_root)
    backend = check_ambia_backend(ambia_root)
    if ambia_root is None:
        raise FileNotFoundError("AMBIA root was not found. Set the AMBIA repository folder.")
    atlas_templates = load_ambia_atlas_templates(ambia_root)
    if not atlas_templates:
        raise FileNotFoundError(f"No AMBIA atlas PNG files were found under: {ambia_root}")

    hint_file = Path(ap_hint_path).resolve() if ap_hint_path and str(ap_hint_path).strip() else None
    ap_hints = load_ap_position_hints(hint_file) if hint_file and hint_file.exists() else []

    if progress_callback:
        progress_callback("Matching sections to AMBIA atlas", 0.58)
    matches = match_sections_to_ambia_atlas(
        converted_images=converted,
        atlas_templates=atlas_templates,
        ap_hints=ap_hints,
        enforce_ap_order=enforce_ap_order,
        qc_dir=output_dir / "qc_overlay",
        logger=logger,
    )
    if not matches:
        raise RuntimeError("AMBIA atlas matching did not produce any section registrations.")

    if progress_callback:
        progress_callback("Writing QDF1-compatible JSON", 0.86)
    qdf_json_path = jpg_dir / "jpgAMBIA_results.json"
    payload = _qdf1_payload(
        [
            {
                "filename": match.converted.output_jpg.name,
                "anchoring": match.anchoring,
                "height": int(_image_size(match.converted.output_jpg)[1]),
                "width": int(_image_size(match.converted.output_jpg)[0]),
                "nr": index,
                "markers": [],
            }
            for index, match in enumerate(matches, start=1)
        ]
    )
    write_prediction_bundle(
        payload=payload,
        json_path=qdf_json_path,
        csv_path=qdf_json_path.with_suffix(".csv"),
        xml_path=qdf_json_path.with_suffix(".xml"),
    )

    match_report_path = output_dir / "QDF1_AMBIA_match_report.csv"
    write_ambia_match_report(matches, match_report_path)
    ap_hint_template = output_dir / "ap_hint_template.csv"
    write_ap_hint_template(converted, ap_hint_template)
    status = "ok"
    status_path = output_dir / "QDF1_AMBIA_method_status.json"
    status_payload = {
        "method": "AMBIA",
        "status": status,
        "input_dir": str(input_dir),
        "registration_channel": channel.strip().upper(),
        "secondary_channel": secondary_channel.strip().upper() if secondary_channel else "",
        "jpg_dir": str(jpg_dir),
        "ambia_root": str(ambia_root) if ambia_root else "",
        "backend": backend,
        "ap_hint_path": str(hint_file) if hint_file else "",
        "enforce_ap_order": bool(enforce_ap_order),
        "qdf_json_path": str(qdf_json_path),
        "match_report": str(match_report_path),
        "ap_hint_template": str(ap_hint_template),
        "qdf_json_created": True,
        "notes": [
            "QDF1-AMBIA uses AMBIA's Allen/AMBIA coronal atlas PNG stack to select AP position by DAPI tissue-mask shape matching.",
            "The QDF1 JSON stores the selected AP plane plus bbox-derived scale/translation in QuickNII's 9-value anchoring field.",
            "AMBIA's non-linear Ardent deformation cannot be represented exactly in QuickNII JSON; it should be treated as QC/refinement rather than the JSON transform itself.",
            "The local AMBIA ONNX smart-localization models were not found, so atlas-shape matching was used.",
        ],
    }
    status_path.write_text(json.dumps(status_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    report_path = output_dir / "QDF1_AMBIA_registration_report.md"
    report_path.write_text(_ambia_report(status_payload, matches=matches), encoding="utf-8")
    logger.info("QDF1-AMBIA JSON written: %s", qdf_json_path)
    if progress_callback:
        progress_callback("Done", 1.0)
    return AlternativeRegistrationResult(
        method="AMBIA",
        input_dir=input_dir,
        output_dir=output_dir,
        jpg_dir=jpg_dir,
        status_path=status_path,
        report_path=report_path,
        qdf_json_path=qdf_json_path,
        converted_images=converted,
        status=status,
    )


def check_ambia_backend(ambia_root: Path | None) -> dict[str, object]:
    """Return a conservative local AMBIA backend readiness check."""

    if ambia_root is None:
        return {
            "adapter_can_run": False,
            "can_run_onnx_smart_localization": False,
            "reason": "AMBIA root was not found.",
            "missing": ["AMBIA repository"],
        }
    model_dir = ambia_root / "mb_gui" / "models"
    atlas_dir = ambia_root / "Gui_Atlases" / "Adult_full_atlases" / "unlabeled_atlases"
    expected_models = [
        model_dir / "single_regression_resnet50v2_v11.onnx",
        model_dir / "quadrant_regression_resnet101_v2.onnx",
        model_dir / "SGC_V6.onnx",
    ]
    missing = [str(path) for path in expected_models if not path.exists()]
    ardent_available = importlib.util.find_spec("ardent") is not None
    onnxruntime_available = importlib.util.find_spec("onnxruntime") is not None
    can_run = not missing and onnxruntime_available
    atlas_available = atlas_dir.exists() and any(atlas_dir.glob("*.png"))
    return {
        "adapter_can_run": bool(atlas_available),
        "atlas_stack_available": bool(atlas_available),
        "can_run_onnx_smart_localization": bool(can_run),
        "ambia_root_exists": ambia_root.exists(),
        "ardent_available": ardent_available,
        "onnxruntime_available": onnxruntime_available,
        "missing": missing,
        "reason": "" if can_run else "AMBIA ONNX smart-localization models and/or onnxruntime are not available; atlas-stack matching will be used.",
    }


def load_ambia_atlas_templates(ambia_root: Path) -> list[AmbiaAtlasTemplate]:
    """Load AMBIA coronal atlas masks for AP shape matching."""

    atlas_dir = ambia_root / "Gui_Atlases" / "Adult_full_atlases" / "unlabeled_atlases"
    templates: list[AmbiaAtlasTemplate] = []
    for path in sorted(atlas_dir.glob("*.png"), key=lambda item: _safe_int(item.stem)):
        atlas_num = _safe_int(path.stem)
        if atlas_num < AMBIA_ATLAS_SLICE_MIN or atlas_num > AMBIA_ATLAS_SLICE_MAX:
            continue
        image = _read_grayscale_uint8(path)
        if image.size == 0:
            continue
        mask = (image > 5).astype(np.uint8)
        mask = _clean_binary_mask(mask)
        bbox = _mask_bbox(mask)
        signature = _mask_signature(mask, bbox)
        templates.append(
            AmbiaAtlasTemplate(
                atlas_num=atlas_num,
                image_path=path,
                mask=mask,
                signature=signature,
                bbox=bbox,
                shape=mask.shape,
            )
        )
    return templates


def match_sections_to_ambia_atlas(
    *,
    converted_images: list[ConvertedJpg],
    atlas_templates: list[AmbiaAtlasTemplate],
    ap_hints: list[object],
    enforce_ap_order: bool,
    qc_dir: Path,
    logger: logging.Logger | None = None,
) -> list[AmbiaSliceMatch]:
    """Match converted section JPEGs to the AMBIA atlas stack."""

    logger = logger or LOG
    qc_dir.mkdir(parents=True, exist_ok=True)
    for stale_overlay in qc_dir.glob("*_AMBIA_atlas*_overlay.jpg"):
        try:
            stale_overlay.unlink()
        except OSError:
            pass
    hint_lookup = _build_hint_lookup(ap_hints)
    atlas_nums = [template.atlas_num for template in atlas_templates]
    score_rows: list[list[float]] = []
    source_masks: list[np.ndarray] = []
    source_bboxes: list[tuple[int, int, int, int]] = []
    top_candidates_by_image: list[list[tuple[int, float]]] = []

    for item in converted_images:
        image = _read_grayscale_uint8(item.output_jpg)
        if image.size == 0:
            raise FileNotFoundError(f"Could not read JPEG: {item.output_jpg}")
        source_mask = tissue_mask_from_grayscale(image)
        source_bbox = _mask_bbox(source_mask)
        source_signature = _mask_signature(source_mask, source_bbox)
        hint = _hint_for_image(item.output_jpg.name, hint_lookup)
        scores: list[float] = []
        for template in atlas_templates:
            score = _score_mask_signature(source_signature, source_bbox, template.signature, template.bbox)
            if hint is not None and not _atlas_num_within_hint(template.atlas_num, hint):
                score -= 2.0
            scores.append(float(score))
        ordered = sorted(zip(atlas_nums, scores), key=lambda row: row[1], reverse=True)
        score_rows.append(scores)
        source_masks.append(source_mask)
        source_bboxes.append(source_bbox)
        top_candidates_by_image.append([(int(num), float(score)) for num, score in ordered[:5]])

    selected_indices = _select_ambia_atlas_indices(np.asarray(score_rows, dtype=np.float64), enforce_ap_order)
    matches: list[AmbiaSliceMatch] = []
    for item_index, template_index in enumerate(selected_indices):
        item = converted_images[item_index]
        template = atlas_templates[template_index]
        width, height = _image_size(item.output_jpg)
        anchoring = qdf1_anchoring_from_ambia_match(
            atlas_num=template.atlas_num,
            source_width=width,
            source_height=height,
            source_bbox=source_bboxes[item_index],
            atlas_bbox=template.bbox,
            atlas_shape=template.shape,
        )
        overlay_path = qc_dir / f"{item.output_jpg.stem}_AMBIA_atlas{template.atlas_num:03d}_overlay.jpg"
        write_ambia_qc_overlay(
            image_path=item.output_jpg,
            source_mask=source_masks[item_index],
            atlas_mask=template.mask,
            source_bbox=source_bboxes[item_index],
            atlas_bbox=template.bbox,
            output_path=overlay_path,
        )
        match = AmbiaSliceMatch(
            converted=item,
            atlas_num=template.atlas_num,
            score=float(score_rows[item_index][template_index]),
            anchoring=anchoring,
            source_bbox=source_bboxes[item_index],
            atlas_bbox=template.bbox,
            top_candidates=top_candidates_by_image[item_index],
            ap_mm=ambia_atlas_num_to_ap_mm(template.atlas_num),
            qc_overlay_path=overlay_path,
        )
        matches.append(match)
        logger.info(
            "AMBIA matched %s -> atlas %03d (AP %.2f mm, score %.3f)",
            item.output_jpg.name,
            template.atlas_num,
            match.ap_mm,
            match.score,
        )
    return matches


def tissue_mask_from_grayscale(image: np.ndarray) -> np.ndarray:
    """Create a broad tissue mask from an enhanced grayscale section image."""

    gray = image.astype(np.float32, copy=False)
    if gray.size == 0 or float(np.max(gray)) <= 0.0:
        return np.zeros(gray.shape, dtype=np.uint8)
    max_side = max(gray.shape[:2])
    scale = min(1.0, 640.0 / float(max_side))
    if scale < 1.0:
        small = transform.resize(
            gray,
            (max(1, int(round(gray.shape[0] * scale))), max(1, int(round(gray.shape[1] * scale)))),
            order=1,
            mode="edge",
            preserve_range=True,
            anti_aliasing=True,
        ).astype(np.float32)
    else:
        small = gray
    blurred = ndi.gaussian_filter(small, sigma=max(2.0, min(small.shape[:2]) / 45.0))
    positive = blurred[blurred > 0]
    if positive.size == 0:
        return np.zeros(gray.shape, dtype=np.uint8)
    try:
        otsu_threshold = float(filters.threshold_otsu(blurred))
    except ValueError:
        otsu_threshold = float(np.percentile(positive, 50))
    floor_threshold = max(3.0, float(np.percentile(positive, 18)))
    ceiling_threshold = float(np.percentile(positive, 82))
    threshold = min(max(otsu_threshold * 0.45, floor_threshold), ceiling_threshold)
    mask_small = blurred >= threshold
    close_size = max(5, int(round(min(small.shape[:2]) / 45.0)))
    mask_small = ndi.binary_closing(mask_small, structure=np.ones((close_size, close_size), dtype=bool), iterations=2)
    mask_small = ndi.binary_fill_holes(mask_small)
    mask_small = ndi.binary_opening(mask_small, structure=np.ones((3, 3), dtype=bool), iterations=1)
    if scale < 1.0:
        mask = _resize_nearest(mask_small.astype(np.uint8), gray.shape[0], gray.shape[1])
    else:
        mask = mask_small.astype(np.uint8)
    return _clean_binary_mask(mask)


def qdf1_anchoring_from_ambia_match(
    *,
    atlas_num: int,
    source_width: int,
    source_height: int,
    source_bbox: tuple[int, int, int, int],
    atlas_bbox: tuple[int, int, int, int],
    atlas_shape: tuple[int, int],
    target_resolution: tuple[int, int, int] = QDF1_MOUSE_TARGET_RESOLUTION,
) -> list[float]:
    """Build QuickNII anchoring from AMBIA AP slice and mask bbox alignment."""

    target_x, target_y, target_z = (float(value) for value in target_resolution)
    atlas_h, atlas_w = (float(value) for value in atlas_shape)
    sx0, sy0, sx1, sy1 = [float(value) for value in source_bbox]
    ax0, ay0, ax1, ay1 = [float(value) for value in atlas_bbox]
    sx_span = max(sx1 - sx0, 1.0)
    sy_span = max(sy1 - sy0, 1.0)

    def atlas_x_to_quicknii(x_value: float) -> float:
        scaled = x_value / max(atlas_w - 1.0, 1.0)
        return (target_x - 1.0) * (1.0 - scaled)

    def atlas_y_to_quicknii(y_value: float) -> float:
        scaled = y_value / max(atlas_h - 1.0, 1.0)
        return (target_z - 1.0) * (1.0 - scaled)

    left_x = atlas_x_to_quicknii(ax0)
    right_x = atlas_x_to_quicknii(ax1)
    top_z = atlas_y_to_quicknii(ay0)
    bottom_z = atlas_y_to_quicknii(ay1)
    u_x = (right_x - left_x) * float(source_width) / sx_span
    v_z = (bottom_z - top_z) * float(source_height) / sy_span
    origin_x = left_x - u_x * sx0 / max(float(source_width), 1.0)
    origin_z = top_z - v_z * sy0 / max(float(source_height), 1.0)
    origin_y = ambia_atlas_num_to_quicknii_y(atlas_num, target_resolution=target_resolution)
    return [
        float(origin_x),
        float(origin_y),
        float(origin_z),
        float(u_x),
        0.0,
        0.0,
        0.0,
        0.0,
        float(v_z),
    ]


def ambia_atlas_num_to_quicknii_y(
    atlas_num: int,
    *,
    target_resolution: tuple[int, int, int] = QDF1_MOUSE_TARGET_RESOLUTION,
) -> float:
    """Convert AMBIA atlas number to QuickNII AP-axis voxel coordinate."""

    ap_index_10um = (float(atlas_num) * 10.0) - 7.0
    ap_index_target = (ap_index_10um * 10.0) / QDF1_MOUSE_VOXEL_SIZE_UM
    return float(target_resolution[1] - 1) - ap_index_target


def ambia_atlas_num_to_ap_mm(atlas_num: int) -> float:
    """Convert AMBIA atlas number to bregma-relative AP in millimeters."""

    ap_index_10um = (float(atlas_num) * 10.0) - 7.0
    ap_um = QDF1_MOUSE_BREGMA_X_UM - (ap_index_10um * 10.0)
    return ap_um / 1000.0


def write_ambia_match_report(matches: list[AmbiaSliceMatch], output_path: Path) -> Path:
    """Write per-section AMBIA matching diagnostics."""

    rows = []
    for match in matches:
        rows.append(
            {
                "filename": match.converted.output_jpg.name,
                "section_id": extract_section_id(match.converted.output_jpg.name),
                "atlas_num": match.atlas_num,
                "ap_mm": match.ap_mm,
                "score": match.score,
                "source_bbox": ",".join(str(value) for value in match.source_bbox),
                "atlas_bbox": ",".join(str(value) for value in match.atlas_bbox),
                "top_candidates": ";".join(f"{num}:{score:.4f}" for num, score in match.top_candidates),
                "qc_overlay": str(match.qc_overlay_path) if match.qc_overlay_path else "",
            }
        )
    pd.DataFrame(rows).to_csv(output_path, index=False)
    return output_path


def write_ambia_qc_overlay(
    *,
    image_path: Path,
    source_mask: np.ndarray,
    atlas_mask: np.ndarray,
    source_bbox: tuple[int, int, int, int],
    atlas_bbox: tuple[int, int, int, int],
    output_path: Path,
) -> None:
    """Overlay transformed AMBIA atlas outline on the source image for QC."""

    image = _read_grayscale_uint8(image_path)
    if image.size == 0:
        return
    rgb = np.stack([image, image, image], axis=-1)
    sx0, sy0, sx1, sy1 = source_bbox
    ax0, ay0, ax1, ay1 = atlas_bbox
    crop = atlas_mask[max(ay0, 0) : max(ay1, ay0 + 1), max(ax0, 0) : max(ax1, ax0 + 1)]
    target_w = max(int(sx1 - sx0), 1)
    target_h = max(int(sy1 - sy0), 1)
    atlas_resized = _resize_nearest(crop.astype(np.uint8), target_h, target_w)
    canvas = np.zeros_like(source_mask, dtype=np.uint8)
    y_end = min(sy0 + target_h, canvas.shape[0])
    x_end = min(sx0 + target_w, canvas.shape[1])
    canvas[sy0:y_end, sx0:x_end] = atlas_resized[: y_end - sy0, : x_end - sx0]
    pil_image = Image.fromarray(rgb, mode="RGB")
    draw = ImageDraw.Draw(pil_image)
    _draw_mask_contours(draw, canvas, color=(255, 255, 0), width=3)
    _draw_mask_contours(draw, source_mask.astype(np.uint8), color=(0, 180, 255), width=1)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pil_image.save(output_path, quality=82, optimize=True)


def _read_grayscale_uint8(path: Path) -> np.ndarray:
    """Read an image as 8-bit grayscale without requiring OpenCV."""

    try:
        with Image.open(path) as image:
            return np.asarray(image.convert("L"), dtype=np.uint8)
    except Exception:
        return np.zeros((0, 0), dtype=np.uint8)


def _resize_nearest(mask: np.ndarray, height: int, width: int) -> np.ndarray:
    if height <= 0 or width <= 0:
        return np.zeros((max(height, 0), max(width, 0)), dtype=np.uint8)
    resized = transform.resize(
        mask.astype(np.uint8),
        (int(height), int(width)),
        order=0,
        mode="edge",
        preserve_range=True,
        anti_aliasing=False,
    )
    return (resized > 0.5).astype(np.uint8)


def _draw_mask_contours(draw: ImageDraw.ImageDraw, mask: np.ndarray, *, color: tuple[int, int, int], width: int) -> None:
    for contour in measure.find_contours(mask.astype(np.uint8), level=0.5):
        if contour.shape[0] < 2:
            continue
        points = [(float(col), float(row)) for row, col in contour]
        draw.line(points, fill=color, width=width, joint="curve")


def _clean_binary_mask(mask: np.ndarray) -> np.ndarray:
    mask = (mask > 0).astype(np.uint8)
    mask_bool = ndi.binary_closing(mask > 0, structure=np.ones((5, 5), dtype=bool), iterations=2)
    mask_bool = ndi.binary_fill_holes(mask_bool)
    mask_bool = ndi.binary_opening(mask_bool, structure=np.ones((3, 3), dtype=bool), iterations=1)
    labels, num_labels = ndi.label(mask_bool)
    if num_labels <= 1:
        return mask
    areas = np.bincount(labels.ravel())[1:]
    if areas.size == 0:
        return mask
    min_area = max(float(np.max(areas)) * 0.05, mask.size * 0.002)
    keep = np.zeros(num_labels, dtype=bool)
    keep[areas >= min_area] = True
    cleaned = np.zeros_like(labels, dtype=np.uint8)
    for label_index, should_keep in enumerate(keep, start=1):
        if should_keep:
            cleaned[labels == label_index] = 1
    return cleaned


def _mask_bbox(mask: np.ndarray) -> tuple[int, int, int, int]:
    ys, xs = np.where(mask > 0)
    if xs.size == 0 or ys.size == 0:
        return (0, 0, int(mask.shape[1]), int(mask.shape[0]))
    return (int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1)


def _mask_signature(mask: np.ndarray, bbox: tuple[int, int, int, int]) -> np.ndarray:
    x0, y0, x1, y1 = bbox
    crop = mask[max(y0, 0) : max(y1, y0 + 1), max(x0, 0) : max(x1, x0 + 1)]
    return _resize_mask_with_padding(crop, AMBIA_MATCH_SIZE)


def _resize_mask_with_padding(mask: np.ndarray, size: int) -> np.ndarray:
    mask = (mask > 0).astype(np.uint8)
    h, w = mask.shape[:2]
    if h <= 0 or w <= 0:
        return np.zeros((size, size), dtype=np.uint8)
    scale = min(size / float(w), size / float(h))
    new_w = max(1, int(round(w * scale)))
    new_h = max(1, int(round(h * scale)))
    resized = _resize_nearest(mask, new_h, new_w)
    canvas = np.zeros((size, size), dtype=np.uint8)
    x0 = (size - new_w) // 2
    y0 = (size - new_h) // 2
    canvas[y0 : y0 + new_h, x0 : x0 + new_w] = resized
    return canvas


def _score_mask_signature(
    source_signature: np.ndarray,
    source_bbox: tuple[int, int, int, int],
    atlas_signature: np.ndarray,
    atlas_bbox: tuple[int, int, int, int],
) -> float:
    source_bool = source_signature > 0
    atlas_bool = atlas_signature > 0
    union = np.logical_or(source_bool, atlas_bool).sum()
    if union == 0:
        return -1.0
    intersection = np.logical_and(source_bool, atlas_bool).sum()
    iou = float(intersection) / float(union)
    source_edge = feature.canny(source_signature.astype(bool), sigma=1.0)
    atlas_edge = feature.canny(atlas_signature.astype(bool), sigma=1.0)
    atlas_dist = ndi.distance_transform_edt(~atlas_edge)
    source_dist = ndi.distance_transform_edt(~source_edge)
    chamfer_terms = []
    if source_edge.any():
        chamfer_terms.append(float(np.mean(atlas_dist[source_edge])) / AMBIA_MATCH_SIZE)
    if atlas_edge.any():
        chamfer_terms.append(float(np.mean(source_dist[atlas_edge])) / AMBIA_MATCH_SIZE)
    chamfer = float(np.mean(chamfer_terms)) if chamfer_terms else 1.0
    sx0, sy0, sx1, sy1 = source_bbox
    ax0, ay0, ax1, ay1 = atlas_bbox
    source_aspect = max(sx1 - sx0, 1) / max(sy1 - sy0, 1)
    atlas_aspect = max(ax1 - ax0, 1) / max(ay1 - ay0, 1)
    aspect_penalty = min(abs(math.log(max(source_aspect, 1e-6) / max(atlas_aspect, 1e-6))), 1.0)
    return (0.78 * iou) + (0.22 * (1.0 - min(chamfer, 1.0))) - (0.08 * aspect_penalty)


def _select_ambia_atlas_indices(score_matrix: np.ndarray, enforce_ap_order: bool) -> list[int]:
    if score_matrix.size == 0:
        return []
    if not enforce_ap_order or score_matrix.shape[0] == 1:
        return [int(np.argmax(row)) for row in score_matrix]
    n_sections, n_templates = score_matrix.shape
    dp = np.full((n_sections, n_templates), -np.inf, dtype=np.float64)
    prev = np.zeros((n_sections, n_templates), dtype=np.int32)
    dp[0] = score_matrix[0]
    jump_penalty = 0.0025
    for row in range(1, n_sections):
        for col in range(n_templates):
            candidates = dp[row - 1, : col + 1] - (jump_penalty * np.abs(np.arange(col + 1) - col))
            best_prev = int(np.argmax(candidates))
            dp[row, col] = score_matrix[row, col] + candidates[best_prev]
            prev[row, col] = best_prev
    selected = [0] * n_sections
    selected[-1] = int(np.argmax(dp[-1]))
    for row in range(n_sections - 1, 0, -1):
        selected[row - 1] = int(prev[row, selected[row]])
    return selected


def _build_hint_lookup(hints: list[object]) -> dict[str, object]:
    lookup: dict[str, object] = {}
    for hint in hints:
        filename_stem = getattr(hint, "filename_stem", None)
        section_id = getattr(hint, "section_id", None)
        if filename_stem:
            lookup[str(filename_stem).lower()] = hint
        if section_id:
            lookup[str(section_id).lower()] = hint
    return lookup


def _hint_for_image(filename: str, hint_lookup: dict[str, object]) -> object | None:
    stem = Path(filename).stem.lower()
    section_id = extract_section_id(filename)
    return hint_lookup.get(stem) or (hint_lookup.get(section_id.lower()) if section_id else None)


def _atlas_num_within_hint(atlas_num: int, hint: object) -> bool:
    expected_ap = float(getattr(hint, "ap_mm"))
    tolerance = float(getattr(hint, "tolerance_mm", 0.35))
    return abs(ambia_atlas_num_to_ap_mm(atlas_num) - expected_ap) <= max(tolerance, 0.0)


def write_ap_hint_template(converted_images: list[ConvertedJpg], output_path: Path) -> Path:
    """Create a fill-in AP hint CSV for the converted section list."""

    rows = []
    for item in converted_images:
        rows.append(
            {
                "slice_id_or_filename": extract_section_id(item.output_jpg.name) or item.output_jpg.name,
                "ap_mm": "",
                "tolerance_mm": 0.35,
                "filename": item.output_jpg.name,
            }
        )
    pd.DataFrame(rows).to_csv(output_path, index=False)
    return output_path


def _prepare_qdf_jpegs(
    input_dir: Path,
    channel: str,
    jpg_dir: Path,
    *,
    logger: logging.Logger,
) -> list[ConvertedJpg]:
    channel = channel.strip().upper()
    tiff_paths = discover_channel_tiffs(input_dir, channel)
    if not tiff_paths:
        raise FileNotFoundError(f"No TIFF files for {channel} found in {input_dir}")
    return convert_tiffs_to_jpgs(tiff_paths, jpg_dir, logger=logger)


def _resolve_ambia_root(ambia_root: Path | None) -> Path | None:
    if ambia_root and str(ambia_root).strip():
        return Path(ambia_root).resolve()
    candidates = [
        os.environ.get("QDF_AMBIA_ROOT", ""),
        str(Path.home() / "AMBIA" / "AMBIA"),
        str(Path(__file__).resolve().parents[1] / "external_methods" / "AMBIA"),
    ]
    for candidate_text in candidates:
        if not candidate_text:
            continue
        candidate = Path(candidate_text).resolve()
        if (candidate / "Gui_Atlases" / "Adult_full_atlases").exists():
            return candidate
    return None


def _safe_int(value: object) -> int:
    try:
        return int(value)
    except Exception:
        return 0


def _image_size(path: Path) -> tuple[int, int]:
    with Image.open(path) as image:
        return image.size


def _qdf1_payload(slices: list[dict[str, object]]) -> dict[str, object]:
    payload = {
        "name": "",
        "target": QDF1_MOUSE_TARGET,
        "target-resolution": list(QDF1_MOUSE_TARGET_RESOLUTION),
        "slices": slices,
    }
    return sanitize_payload_for_quicknii(payload=payload, default_name="QDF1_alternative")


def _ambia_report(status_payload: dict[str, object], *, matches: list[AmbiaSliceMatch] | None = None) -> str:
    backend = status_payload.get("backend", {})
    match_lines: list[str] = []
    for match in (matches or [])[:8]:
        match_lines.append(
            f"- `{match.converted.output_jpg.name}` -> AMBIA atlas `{match.atlas_num:03d}` "
            f"(AP {match.ap_mm:.2f} mm, score {match.score:.3f})"
        )
    if matches and len(matches) > len(match_lines):
        match_lines.append(f"- ... {len(matches) - len(match_lines)} more sections")
    return "\n".join(
        [
            "# QDF1-AMBIA registration report",
            "",
            f"Status: `{status_payload.get('status')}`",
            f"Input: `{status_payload.get('input_dir')}`",
            f"Prepared JPEGs: `{status_payload.get('jpg_dir')}`",
            f"QDF1 JSON: `{status_payload.get('qdf_json_path')}`",
            f"Match report: `{status_payload.get('match_report')}`",
            "",
            "## Backend check",
            "",
            "```json",
            json.dumps(backend, ensure_ascii=False, indent=2),
            "```",
            "",
            "## Interpretation",
            "",
            "This adapter uses the local AMBIA atlas PNG stack to estimate each section's AP plane by tissue-mask shape matching, then writes the result in the same QuickNII/QDF1 JSON structure produced by QDF1 DeepSlice.",
            "",
            "The local AMBIA checkout does not currently include the ONNX smart-localization models, so the adapter falls back to atlas-stack shape matching. AMBIA/Ardent non-linear 2D deformation is useful for QC/refinement, but it cannot be represented exactly in QuickNII's 9-value anchoring JSON.",
            "",
            "## First matches",
            "",
            *(match_lines or ["- No matches recorded."]),
            "",
        ]
    )
