"""AP-limited atlas edge refinement for QDF1/DeepSlice outputs.

The first implementation intentionally keeps the output schema compatible with
QuickNII/QDF2: DeepSlice is still used to prepare the normal prediction bundle,
then this module rewrites a copy after scoring AP-limited Allen CCF coronal
templates against the section tissue edge.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
import logging
import math
import shutil
from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
from scipy import ndimage as ndi
from skimage import feature, filters, morphology, transform

from atlas.repository import AtlasRepository
from config.settings import AtlasConfig
from deepslice.pipeline import (
    DEEPSLICE_MOUSE_BREGMA_UM,
    DEEPSLICE_MOUSE_QUICKNII_RESOLUTION,
    DEEPSLICE_MOUSE_VOXEL_SIZE_UM,
    DeepSliceApHint,
    DeepSliceRunResult,
    build_ap_hint_lookup,
    estimate_slice_ap_mm,
    extract_section_id,
    load_ap_position_hints,
    normalize_slice_lookup_key,
    run_deepslice_job,
    run_deepslice_predictions,
    sanitize_payload_for_quicknii,
    build_ap_hint_report,
    normalize_prediction_outputs,
    write_prediction_bundle,
)
from registration_adapters.alternative_pipeline import (
    AMBIA_MATCH_SIZE,
    _draw_mask_contours,
    _mask_bbox,
    _mask_signature,
    _read_grayscale_uint8,
    _resize_nearest,
    _score_mask_signature,
    tissue_mask_from_grayscale,
)

LOG = logging.getLogger(__name__)

QDF1_EVO_TARGET = "ABA_Mouse_CCFv3_2017_25um.cutlas"
QDF1_EVO_OUTPUT_STEM = "QDFevo1_results"
OBSOLETE_QDFEVO_OUTPUT_NAMES = (
    "jpgDS_results.json",
    "jpgDS_results.csv",
    "jpgDS_results.xml",
    "jpgDS_ap_hint_report.csv",
    "jpgDS_evo_results.json",
    "jpgDS_evo_results.csv",
    "jpgDS_evo_results.xml",
    "jpgDS_evo_results_ap_hint_report.csv",
    "jpgDS_evo_results_ap_constrained_report.csv",
    "jpgDS_evo_results_input_cleanup_report.csv",
    "jpgDS_evo_results_edge_refine_report.csv",
    "jpgDS_evo_results_final_fit_report.csv",
    "jpgDS_evo_results_teacher_comparison.csv",
    "jpgDS_evo_results_ap_constrained_teacher_metrics.csv",
)
DEFAULT_NO_HINT_SEARCH_MM = 0.60
DEFAULT_AP_STEP_VOX = 1
DEFAULT_AP_PRIOR_WEIGHT = 0.06
DEFAULT_FIT_PREVIEW_MAX_SIDE = 320
DEFAULT_QC_MAX_SIDE = 1400
DEFAULT_CLEANUP_PREVIEW_MAX_SIDE = 900
DEFAULT_CLEANUP_COMPONENT_KEEP_FRACTION = 0.05
DEFAULT_CLEANUP_MIN_ATLAS_KEEP_FRACTION = 0.45
DEFAULT_CLEANUP_ATLAS_MARGIN_FRACTION = 0.09
DEFAULT_CLEANUP_JPEG_QUALITY = 88
DEFAULT_FINAL_FIT_PREVIEW_MAX_SIDE = 420
DEFAULT_FINAL_FIT_MIN_SCORE_GAIN = 0.002


@dataclass(slots=True)
class CcfCoronalTemplate:
    """One CCF coronal plane prepared for 2D tissue-edge matching."""

    quicknii_y: int
    ap_mm: float
    mask: np.ndarray
    bbox: tuple[int, int, int, int]
    signature: np.ndarray


@dataclass(slots=True)
class SliceEdgeRefineResult:
    """Refinement diagnostics for one section."""

    filename: str
    section_id: str | None
    predicted_ap_mm: float
    refined_ap_mm: float
    hint_ap_mm: float | None
    hint_tolerance_mm: float | None
    quicknii_y: int
    score: float
    source_bbox: tuple[int, int, int, int]
    atlas_bbox: tuple[int, int, int, int]
    top_candidates: list[tuple[int, float, float]]
    roll_delta_deg: float = 0.0
    scale_factor: float = 1.0
    original_deepslice_score: float = float("nan")
    common_angle_score: float = float("nan")
    qc_overlay_path: Path | None = None


@dataclass(slots=True)
class AnchoringFit:
    """One real rendered-atlas fit candidate."""

    anchoring: list[float]
    quicknii_y: int
    ap_mm: float
    score: float
    source_bbox: tuple[int, int, int, int]
    atlas_bbox: tuple[int, int, int, int]
    top_candidates: list[tuple[int, float, float]]
    roll_delta_deg: float
    scale_factor: float


@dataclass(slots=True)
class FitSlicePreparation:
    """Prepared per-slice data for common-angle atlas fitting."""

    original_slice: dict[str, object]
    constant_angle_slice: dict[str, object]
    image_path: Path
    source_mask: np.ndarray
    fit_source_mask: np.ndarray
    predicted_ap_mm: float
    hint: DeepSliceApHint | None
    candidate_y_values: list[int]
    prior_ap_mm: float
    prior_width_mm: float


@dataclass(slots=True)
class Qdf1EvoRunResult:
    """Artifacts generated by one QDF1 Evo run."""

    input_dir: Path
    jpg_dir: Path
    baseline_json_path: Path
    refined_json_path: Path
    refined_csv_path: Path
    refined_xml_path: Path
    report_path: Path
    qc_dir: Path
    deepslice_result: DeepSliceRunResult | None = None
    teacher_report_path: Path | None = None
    matches: list[SliceEdgeRefineResult] = field(default_factory=list)


@dataclass(slots=True)
class CleanedJpgResult:
    """Diagnostics for one two-pass DeepSlice cleanup image."""

    filename: str
    original_jpg: Path
    cleaned_jpg: Path
    qc_overlay_path: Path
    source_area_px: int
    component_area_px: int
    atlas_mask_area_px: int
    final_keep_area_px: int
    component_count_before: int
    component_count_kept: int
    atlas_keep_fraction: float
    fallback_reason: str


class CcfCoronalTemplateCache:
    """Lazy cache of CCF coronal masks keyed by QuickNII AP voxel."""

    def __init__(self, atlas_root: Path | None = None) -> None:
        root = Path(atlas_root).resolve() if atlas_root else _default_atlas_root()
        self.atlas_root = root
        self.repository = AtlasRepository(
            AtlasConfig(
                name="allen_mouse_ccfv3_2017_25um",
                labels_path=root / "annotation_25.nrrd",
                tree_path=root / "tree.json",
                labels_txt_path=root / "labels.txt",
                voxel_size_um=DEEPSLICE_MOUSE_VOXEL_SIZE_UM,
                quicknii_resolution_vox=DEEPSLICE_MOUSE_QUICKNII_RESOLUTION,
                allen_bregma_um=DEEPSLICE_MOUSE_BREGMA_UM,
            )
        )
        self._labels: np.ndarray | None = None
        self._cache: dict[int, CcfCoronalTemplate] = {}

    @property
    def labels(self) -> np.ndarray:
        if self._labels is None:
            self._labels = self.repository.require_labels()
        return self._labels

    def template(self, quicknii_y: int) -> CcfCoronalTemplate:
        y_value = int(np.clip(round(float(quicknii_y)), 0, self.labels.shape[1] - 1))
        cached = self._cache.get(y_value)
        if cached is not None:
            return cached
        plane = self.labels[:, y_value, :]
        # Template image axes: x/column = ML-like QuickNII X, y/row = DV-like QuickNII Z.
        # The bbox-to-anchoring conversion below uses the same axis convention as the
        # existing AMBIA adapter, including the QuickNII display flips.
        mask = (plane.T > 0).astype(np.uint8)
        mask = _clean_template_mask(mask)
        bbox = _mask_bbox(mask)
        signature = _mask_signature(mask, bbox)
        item = CcfCoronalTemplate(
            quicknii_y=y_value,
            ap_mm=quicknii_y_to_ap_mm(y_value),
            mask=mask,
            bbox=bbox,
            signature=signature,
        )
        self._cache[y_value] = item
        return item


def run_qdf1_evo_job(
    input_dir: Path,
    channel: str,
    *,
    progress_callback: Callable[[str, float], None] | None = None,
    logger: logging.Logger | None = None,
    same_slicing_angle: bool = True,
    ap_hint_path: Path | None = None,
    constrain_to_ap_hints: bool = True,
    teacher_json_path: Path | None = None,
    atlas_root: Path | None = None,
    enable_experimental_edge_refine: bool = False,
) -> Qdf1EvoRunResult:
    """Run AP-constrained DeepSlice, with optional experimental edge refinement."""

    logger = logger or LOG
    if progress_callback:
        progress_callback("Running baseline DeepSlice", 0.08)
    baseline = run_deepslice_job(
        input_dir=input_dir,
        channel=channel,
        progress_callback=_scaled_progress(progress_callback, 0.08, 0.48),
        logger=logger,
        same_slicing_angle=same_slicing_angle,
        ap_hint_path=ap_hint_path,
        ap_hint_mode="disabled",
        constrain_deepslice_to_ap_hints=constrain_to_ap_hints,
        output_stem_name=QDF1_EVO_OUTPUT_STEM,
        ap_hint_report_name=f"{QDF1_EVO_OUTPUT_STEM}_ap_hint_report.csv",
    )
    if not enable_experimental_edge_refine:
        if progress_callback:
            progress_callback("Writing AP-constrained DeepSlice outputs", 0.92)
        refined = write_deepslice_only_evo_outputs(
            baseline=baseline,
            logger=logger,
        )
        if progress_callback:
            progress_callback("Done", 1.0)
        return refined
    if progress_callback:
        progress_callback("Refining with AP-limited CCF edge matching", 0.62)
    refined = refine_deepslice_prediction_json(
        json_path=baseline.json_path,
        jpg_dir=baseline.jpg_dir,
        output_stem=baseline.jpg_dir / QDF1_EVO_OUTPUT_STEM,
        ap_hint_path=ap_hint_path,
        constrain_to_ap_hints=constrain_to_ap_hints,
        atlas_root=atlas_root,
        progress_callback=_scaled_progress(progress_callback, 0.62, 0.94),
        logger=logger,
    )
    refined.deepslice_result = baseline
    teacher_path = Path(teacher_json_path).resolve() if teacher_json_path and str(teacher_json_path).strip() else None
    if teacher_path and teacher_path.exists():
        refined.teacher_report_path = compare_prediction_to_teacher(
            prediction_json_path=refined.refined_json_path,
            teacher_json_path=teacher_path,
            output_path=refined.refined_json_path.with_name(f"{refined.refined_json_path.stem}_teacher_metrics.csv"),
        )
    if progress_callback:
        progress_callback("Done", 1.0)
    return refined


def write_deepslice_only_evo_outputs(
    *,
    baseline: DeepSliceRunResult,
    logger: logging.Logger | None = None,
) -> Qdf1EvoRunResult:
    """Expose the AP-constrained DeepSlice bundle under the QDFevo output names."""

    logger = logger or LOG
    output_stem = baseline.jpg_dir / QDF1_EVO_OUTPUT_STEM
    refined_json = output_stem.with_suffix(".json")
    refined_csv = output_stem.with_suffix(".csv")
    refined_xml = output_stem.with_suffix(".xml")

    payload = json.loads(baseline.json_path.read_text(encoding="utf-8"))
    payload["name"] = output_stem.name
    payload["target"] = QDF1_EVO_TARGET
    write_prediction_bundle(
        payload=payload,
        json_path=refined_json,
        csv_path=refined_csv,
        xml_path=refined_xml,
    )

    report_path = output_stem.with_name(f"{output_stem.name}_ap_hint_report.csv")
    if baseline.ap_hint_report_path is not None and baseline.ap_hint_report_path.exists():
        if baseline.ap_hint_report_path.resolve() != report_path.resolve():
            shutil.copy2(baseline.ap_hint_report_path, report_path)
    else:
        pd.DataFrame(
            columns=[
                "filename",
                "section_id",
                "predicted_ap_mm",
                "expected_ap_mm",
                "tolerance_mm",
                "abs_delta_mm",
                "outside_tolerance",
                "hint_matched",
            ]
        ).to_csv(report_path, index=False)
    remove_obsolete_qdfevo_output_files(
        baseline.jpg_dir,
        keep_paths={refined_json, refined_csv, refined_xml, report_path},
        logger=logger,
    )
    logger.info("QDFevo_1_Align DeepSlice-only outputs written: %s", output_stem)

    return Qdf1EvoRunResult(
        input_dir=baseline.input_dir,
        jpg_dir=baseline.jpg_dir,
        baseline_json_path=baseline.json_path,
        refined_json_path=refined_json,
        refined_csv_path=refined_csv,
        refined_xml_path=refined_xml,
        report_path=report_path,
        qc_dir=baseline.jpg_dir,
        deepslice_result=baseline,
        matches=[],
    )


def remove_obsolete_qdfevo_output_files(
    jpg_dir: Path,
    *,
    keep_paths: set[Path],
    logger: logging.Logger | None = None,
) -> None:
    """Remove old auto-generated QDFevo output names without touching edited JSONs."""

    logger = logger or LOG
    keep_resolved = {Path(path).resolve() for path in keep_paths}
    removed = 0
    for filename in OBSOLETE_QDFEVO_OUTPUT_NAMES:
        path = jpg_dir / filename
        if not path.is_file():
            continue
        if path.resolve() in keep_resolved:
            continue
        path.unlink()
        removed += 1
    if removed:
        logger.info("Removed %d obsolete jpgDS/QDFevo output file(s)", removed)


def run_two_pass_cleanup_deepslice(
    *,
    baseline: DeepSliceRunResult,
    channel: str,
    same_slicing_angle: bool,
    ap_hint_path: Path | None,
    constrain_to_ap_hints: bool,
    atlas_root: Path | None = None,
    progress_callback: Callable[[str, float], None] | None = None,
    logger: logging.Logger | None = None,
) -> Qdf1EvoRunResult:
    """Run DeepSlice again after removing likely adjacent-slice contamination."""

    logger = logger or LOG
    output_stem = baseline.jpg_dir / QDF1_EVO_OUTPUT_STEM
    cleaned_dir = baseline.jpg_dir / "qdf1_evo_cleaned_jpg"
    qc_dir = baseline.jpg_dir / "qdf1_evo_cleanup_qc"
    cleaned_dir.mkdir(parents=True, exist_ok=True)
    qc_dir.mkdir(parents=True, exist_ok=True)

    if progress_callback:
        progress_callback("Preparing atlas-guided cleanup masks", 0.05)
    template_cache = CcfCoronalTemplateCache(atlas_root=atlas_root)
    jpg_paths = [item.output_jpg for item in baseline.converted_images]
    if not jpg_paths:
        payload = json.loads(baseline.json_path.read_text(encoding="utf-8"))
        for item in payload.get("slices", []):
            if isinstance(item, dict):
                filename = str(item.get("filename", "")).strip()
                if filename:
                    jpg_paths.append(baseline.jpg_dir / Path(filename).name)
    cleanup_results = create_atlas_guided_cleaned_jpegs(
        json_path=baseline.json_path,
        jpg_paths=jpg_paths,
        output_dir=cleaned_dir,
        qc_dir=qc_dir,
        template_cache=template_cache,
        progress_callback=_scaled_progress(progress_callback, 0.05, 0.34),
        logger=logger,
    )
    cleanup_report_path = output_stem.with_name(f"{output_stem.name}_input_cleanup_report.csv")
    write_cleanup_report(cleanup_results, cleanup_report_path)
    logger.info("QDF1 Evo input cleanup report written: %s", cleanup_report_path)

    if progress_callback:
        progress_callback("Running DeepSlice on cleaned images", 0.42)
    hints = load_ap_position_hints(Path(ap_hint_path).resolve()) if ap_hint_path and str(ap_hint_path).strip() else []
    runner_ap_hint_path: Path | None = None
    if hints and constrain_to_ap_hints:
        runner_ap_hint_path = _write_runner_ap_hint_json_for_paths(
            image_paths=[item.cleaned_jpg for item in cleanup_results],
            hints=hints,
            output_path=output_stem.parent / ".deepslice_ap_hints_qdf1_evo_cleaned.json",
        )
    runner_script = Path(__file__).resolve().parents[1] / "tools" / "deepslice_predict_runner.py"
    run_deepslice_predictions(
        manifest_paths=[item.cleaned_jpg for item in cleanup_results],
        output_stem=output_stem,
        python_executable=baseline.deepslice_python,
        runner_script=runner_script,
        species="mouse",
        use_ensemble=True,
        same_slicing_angle=same_slicing_angle,
        logger=logger,
        manifest_channel=f"{channel.lower()}_qdf1_evo_cleaned",
        ap_hint_json_path=runner_ap_hint_path,
    )

    refined_json = output_stem.with_suffix(".json")
    refined_csv = output_stem.with_suffix(".csv")
    refined_xml = output_stem.with_suffix(".xml")
    normalize_prediction_outputs(json_path=refined_json, csv_path=refined_csv, xml_path=refined_xml)

    if progress_callback:
        progress_callback("Refining final atlas silhouette", 0.82)
    apply_final_silhouette_refinement(
        json_path=refined_json,
        csv_path=refined_csv,
        xml_path=refined_xml,
        cleaned_jpg_dir=cleaned_dir,
        output_stem=output_stem,
        template_cache=template_cache,
        progress_callback=_scaled_progress(progress_callback, 0.82, 0.94),
        logger=logger,
    )

    if progress_callback:
        progress_callback("Writing AP report", 0.95)
    report_path = output_stem.with_name(f"{output_stem.name}_ap_constrained_report.csv")
    if hints:
        report_frame = build_ap_hint_report(json_path=refined_json, hints=hints, species="mouse")
    else:
        report_frame = pd.DataFrame(
            [
                {
                    "status": "two_pass_cleanup_deepslice",
                    "json": str(refined_json),
                    "input_cleanup_report": str(cleanup_report_path),
                }
            ]
        )
    report_frame.to_csv(report_path, index=False)
    return Qdf1EvoRunResult(
        input_dir=baseline.input_dir,
        jpg_dir=baseline.jpg_dir,
        baseline_json_path=baseline.json_path,
        refined_json_path=refined_json,
        refined_csv_path=refined_csv,
        refined_xml_path=refined_xml,
        report_path=report_path,
        qc_dir=qc_dir,
        deepslice_result=baseline,
    )


def create_atlas_guided_cleaned_jpegs(
    *,
    json_path: Path,
    jpg_paths: list[Path],
    output_dir: Path,
    qc_dir: Path,
    template_cache: CcfCoronalTemplateCache,
    preview_max_side: int = DEFAULT_CLEANUP_PREVIEW_MAX_SIDE,
    component_keep_fraction: float = DEFAULT_CLEANUP_COMPONENT_KEEP_FRACTION,
    min_atlas_keep_fraction: float = DEFAULT_CLEANUP_MIN_ATLAS_KEEP_FRACTION,
    atlas_margin_fraction: float = DEFAULT_CLEANUP_ATLAS_MARGIN_FRACTION,
    progress_callback: Callable[[str, float], None] | None = None,
    logger: logging.Logger | None = None,
) -> list[CleanedJpgResult]:
    """Create cleaned DeepSlice input JPEGs using tissue components plus the rendered atlas silhouette."""

    logger = logger or LOG
    json_path = Path(json_path).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    qc_dir.mkdir(parents=True, exist_ok=True)
    payload = sanitize_payload_for_quicknii(
        payload=json.loads(json_path.read_text(encoding="utf-8")),
        default_name=json_path.stem,
    )
    slice_lookup: dict[str, dict[str, object]] = {}
    for slice_payload in payload.get("slices", []):
        if not isinstance(slice_payload, dict):
            continue
        filename = str(slice_payload.get("filename", "")).strip()
        if filename:
            slice_lookup[normalize_slice_lookup_key(filename)] = slice_payload

    results: list[CleanedJpgResult] = []
    total = max(len(jpg_paths), 1)
    for index, image_path in enumerate(jpg_paths, start=1):
        image_path = Path(image_path).resolve()
        if progress_callback:
            progress_callback(f"Cleaning {image_path.name}", index / total)
        slice_payload = slice_lookup.get(normalize_slice_lookup_key(image_path.name))
        try:
            result = _clean_one_jpg_for_deepslice(
                image_path=image_path,
                slice_payload=slice_payload,
                output_dir=output_dir,
                qc_dir=qc_dir,
                template_cache=template_cache,
                preview_max_side=preview_max_side,
                component_keep_fraction=component_keep_fraction,
                min_atlas_keep_fraction=min_atlas_keep_fraction,
                atlas_margin_fraction=atlas_margin_fraction,
            )
            results.append(result)
        except Exception as exc:
            logger.exception("QDF1 Evo cleanup failed for %s; copying original image", image_path)
            cleaned_path = output_dir / image_path.name
            Image.open(image_path).convert("L").save(cleaned_path, quality=DEFAULT_CLEANUP_JPEG_QUALITY, optimize=True)
            qc_path = qc_dir / f"{image_path.stem}_cleanup_qc.jpg"
            results.append(
                CleanedJpgResult(
                    filename=image_path.name,
                    original_jpg=image_path,
                    cleaned_jpg=cleaned_path,
                    qc_overlay_path=qc_path,
                    source_area_px=0,
                    component_area_px=0,
                    atlas_mask_area_px=0,
                    final_keep_area_px=0,
                    component_count_before=0,
                    component_count_kept=0,
                    atlas_keep_fraction=float("nan"),
                    fallback_reason=f"cleanup_error: {exc}",
                )
            )
    if not results:
        raise RuntimeError("No cleaned JPEGs were created for QDF1 Evo two-pass DeepSlice.")
    return results


def apply_final_silhouette_refinement(
    *,
    json_path: Path,
    csv_path: Path,
    xml_path: Path,
    cleaned_jpg_dir: Path,
    output_stem: Path,
    template_cache: CcfCoronalTemplateCache,
    progress_callback: Callable[[str, float], None] | None = None,
    logger: logging.Logger | None = None,
) -> Path:
    """Refit the final DeepSlice atlas silhouette to the cleaned section mask."""

    logger = logger or LOG
    json_path = Path(json_path).resolve()
    cleaned_jpg_dir = Path(cleaned_jpg_dir).resolve()
    output_stem = Path(output_stem).resolve()
    qc_dir = output_stem.parent / "qdf1_evo_final_fit_qc"
    qc_dir.mkdir(parents=True, exist_ok=True)
    payload = sanitize_payload_for_quicknii(
        payload=json.loads(json_path.read_text(encoding="utf-8")),
        default_name=output_stem.stem,
    )
    slices = [item for item in payload.get("slices", []) if isinstance(item, dict)]
    refined_slices: list[dict[str, object]] = []
    rows: list[dict[str, object]] = []
    total = max(len(slices), 1)
    for index, slice_payload in enumerate(slices, start=1):
        filename = Path(str(slice_payload.get("filename", ""))).name
        if progress_callback:
            progress_callback(f"Final fit {filename or index}", (index - 1) / total)
        image_path = cleaned_jpg_dir / filename
        if not filename or not image_path.exists():
            refined_slices.append(dict(slice_payload))
            rows.append(
                {
                    "filename": filename,
                    "status": "skipped_missing_cleaned_jpg",
                    "accepted": False,
                }
            )
            continue
        source_image = _read_grayscale_uint8(image_path)
        source_mask = tissue_mask_from_grayscale(source_image)
        fit_source_mask, _fit_scale = _downsample_binary_mask(source_mask, max_side=DEFAULT_FINAL_FIT_PREVIEW_MAX_SIDE)
        original_score = _score_slice_anchoring(
            anchoring=slice_payload.get("anchoring", []),
            source_mask_preview=fit_source_mask,
            template_cache=template_cache,
        )
        refined_slice = dict(slice_payload)
        try:
            current_ap = _safe_estimate_ap(slice_payload)
            current_y = int(round(ap_mm_to_quicknii_y(current_ap)))
            fit = _fit_roll_primary_silhouette_to_source(
                baseline_slice=slice_payload,
                target_y=current_y,
                template_cache=template_cache,
                source_mask_preview=fit_source_mask,
            )
            score_gain = float(fit.score) - float(original_score)
            accepted = bool(math.isfinite(score_gain) and score_gain >= DEFAULT_FINAL_FIT_MIN_SCORE_GAIN)
            if accepted:
                refined_slice["anchoring"] = fit.anchoring
                final_meta = {
                    "method": "post_deepslice_silhouette_fit",
                    "score": float(fit.score),
                    "original_score": float(original_score),
                    "score_gain": float(score_gain),
                    "ap_mm": float(fit.ap_mm),
                    "roll_delta_deg": float(fit.roll_delta_deg),
                    "scale_factor": float(fit.scale_factor),
                    "source_bbox_preview": list(fit.source_bbox),
                    "atlas_bbox_preview": list(fit.atlas_bbox),
                }
                existing_meta = refined_slice.get("qdf1_evo")
                if isinstance(existing_meta, dict):
                    existing_meta = dict(existing_meta)
                    existing_meta["final_silhouette_fit"] = final_meta
                    refined_slice["qdf1_evo"] = existing_meta
                else:
                    refined_slice["qdf1_evo"] = {"final_silhouette_fit": final_meta}
                qc_path = qc_dir / f"{Path(filename).stem}_final_silhouette_qc.jpg"
                write_rendered_qc_overlay(
                    image_path=image_path,
                    source_mask=source_mask,
                    anchoring=fit.anchoring,
                    template_cache=template_cache,
                    output_path=qc_path,
                )
            else:
                qc_path = qc_dir / f"{Path(filename).stem}_final_silhouette_qc.jpg"
                write_rendered_qc_overlay(
                    image_path=image_path,
                    source_mask=source_mask,
                    anchoring=list(slice_payload.get("anchoring", [])),
                    template_cache=template_cache,
                    output_path=qc_path,
                )
            rows.append(
                {
                    "filename": filename,
                    "status": "ok",
                    "accepted": accepted,
                    "original_score": float(original_score),
                    "refined_score": float(fit.score),
                    "score_gain": score_gain,
                    "ap_mm_before": float(current_ap),
                    "ap_mm_after": float(fit.ap_mm),
                    "roll_delta_deg": float(fit.roll_delta_deg),
                    "scale_factor": float(fit.scale_factor),
                    "qc_overlay": str(qc_path),
                }
            )
        except Exception as exc:
            logger.exception("Final silhouette fit failed for %s", filename)
            rows.append(
                {
                    "filename": filename,
                    "status": f"fit_failed: {exc}",
                    "accepted": False,
                    "original_score": float(original_score),
                }
            )
        refined_slices.append(refined_slice)

    refined_slices.sort(key=lambda item: -_safe_estimate_ap(item))
    for nr, item in enumerate(refined_slices, start=1):
        item["nr"] = nr
    payload["name"] = output_stem.stem
    payload["target"] = QDF1_EVO_TARGET
    payload["target-resolution"] = list(DEEPSLICE_MOUSE_QUICKNII_RESOLUTION)
    payload["slices"] = refined_slices
    write_prediction_bundle(payload=payload, json_path=json_path, csv_path=csv_path, xml_path=xml_path)
    report_path = output_stem.with_name(f"{output_stem.name}_final_silhouette_report.csv")
    pd.DataFrame(rows).to_csv(report_path, index=False)
    if progress_callback:
        progress_callback("Final silhouette fit complete", 1.0)
    return report_path


def refine_deepslice_prediction_json(
    *,
    json_path: Path,
    jpg_dir: Path | None = None,
    output_stem: Path | None = None,
    ap_hint_path: Path | None = None,
    constrain_to_ap_hints: bool = True,
    atlas_root: Path | None = None,
    no_hint_search_mm: float = DEFAULT_NO_HINT_SEARCH_MM,
    ap_step_vox: int = DEFAULT_AP_STEP_VOX,
    ap_prior_weight: float = DEFAULT_AP_PRIOR_WEIGHT,
    progress_callback: Callable[[str, float], None] | None = None,
    logger: logging.Logger | None = None,
) -> Qdf1EvoRunResult:
    """Rewrite a DeepSlice JSON copy using AP-limited edge matching."""

    logger = logger or LOG
    json_path = Path(json_path).resolve()
    if not json_path.exists():
        raise FileNotFoundError(f"DeepSlice JSON not found: {json_path}")
    jpg_dir = Path(jpg_dir).resolve() if jpg_dir else json_path.parent
    output_stem = Path(output_stem).resolve() if output_stem else json_path.with_name(QDF1_EVO_OUTPUT_STEM)
    output_stem.parent.mkdir(parents=True, exist_ok=True)
    qc_dir = output_stem.parent / "qdf1_evo_qc"
    qc_dir.mkdir(parents=True, exist_ok=True)

    hints = load_ap_position_hints(Path(ap_hint_path).resolve()) if ap_hint_path and str(ap_hint_path).strip() else []
    hint_lookup = build_ap_hint_lookup(hints)
    template_cache = CcfCoronalTemplateCache(atlas_root=atlas_root)

    payload = json.loads(json_path.read_text(encoding="utf-8"))
    payload = sanitize_payload_for_quicknii(payload=payload, default_name=output_stem.stem)
    slices = [item for item in payload.get("slices", []) if isinstance(item, dict)]
    if not slices:
        raise ValueError(f"No slices found in DeepSlice JSON: {json_path}")

    constant_angle_slices = _constant_angle_slice_payloads(slices)
    prepared_slices: list[FitSlicePreparation] = []
    total = max(len(slices), 1)
    for index, (slice_payload, constant_slice) in enumerate(zip(slices, constant_angle_slices), start=1):
        filename = str(slice_payload.get("filename", ""))
        if progress_callback:
            progress_callback(f"Preparing {filename or index}", (index - 1) / total * 0.22)
        image_path = jpg_dir / Path(filename).name
        if not image_path.exists():
            raise FileNotFoundError(f"Slice image referenced by JSON was not found: {image_path}")
        source_image = _read_grayscale_uint8(image_path)
        source_mask = tissue_mask_from_grayscale(source_image)
        fit_source_mask, _fit_scale = _downsample_binary_mask(source_mask, max_side=DEFAULT_FIT_PREVIEW_MAX_SIDE)
        predicted_ap = _safe_estimate_ap(slice_payload)
        hint = _hint_for_slice(filename, hint_lookup)
        candidate_y_values, prior_ap, prior_width_mm = _candidate_y_values(
            predicted_ap_mm=predicted_ap,
            hint=hint if constrain_to_ap_hints else None,
            no_hint_search_mm=no_hint_search_mm,
            ap_step_vox=ap_step_vox,
            max_y=template_cache.labels.shape[1] - 1,
        )
        prepared_slices.append(
            FitSlicePreparation(
                original_slice=slice_payload,
                constant_angle_slice=constant_slice,
                image_path=image_path,
                source_mask=source_mask,
                fit_source_mask=fit_source_mask,
                predicted_ap_mm=predicted_ap,
                hint=hint,
                candidate_y_values=candidate_y_values,
                prior_ap_mm=prior_ap,
                prior_width_mm=prior_width_mm,
            )
        )

    global_roll_delta = _estimate_global_roll_delta(
        prepared_slices=prepared_slices,
        template_cache=template_cache,
        ap_prior_weight=ap_prior_weight,
    )
    logger.info("QDF1 Evo common-angle roll delta: %.3f deg", global_roll_delta)

    refined_slices: list[dict[str, object]] = []
    matches: list[SliceEdgeRefineResult] = []
    for index, prepared in enumerate(prepared_slices, start=1):
        slice_payload = prepared.original_slice
        filename = str(slice_payload.get("filename", ""))
        if progress_callback:
            progress_callback(f"Refining {filename or index}", 0.22 + ((index - 1) / total * 0.76))
        fit = _fit_real_rendered_atlas_to_source(
            baseline_slice=prepared.constant_angle_slice,
            candidate_y_values=prepared.candidate_y_values,
            template_cache=template_cache,
            source_mask_preview=prepared.fit_source_mask,
            prior_ap_mm=prepared.prior_ap_mm,
            prior_width_mm=prepared.prior_width_mm,
            ap_prior_weight=ap_prior_weight,
            fixed_roll_delta_deg=global_roll_delta,
        )
        original_score = _score_slice_anchoring(
            anchoring=prepared.original_slice.get("anchoring", []),
            source_mask_preview=prepared.fit_source_mask,
            template_cache=template_cache,
        )
        common_angle_score = _score_slice_anchoring(
            anchoring=prepared.constant_angle_slice.get("anchoring", []),
            source_mask_preview=prepared.fit_source_mask,
            template_cache=template_cache,
        )
        refined_slice = dict(slice_payload)
        refined_slice["anchoring"] = fit.anchoring
        refined_slice["qdf1_evo"] = {
            "method": "ap_limited_common_angle_rendered_atlas_refine",
            "score": float(fit.score),
            "quicknii_y": int(fit.quicknii_y),
            "ap_mm": float(fit.ap_mm),
            "source_bbox_preview": list(fit.source_bbox),
            "atlas_bbox_preview": list(fit.atlas_bbox),
            "roll_delta_deg": float(fit.roll_delta_deg),
            "common_roll_delta_deg": float(global_roll_delta),
            "scale_factor": float(fit.scale_factor),
        }
        refined_slices.append(refined_slice)
        overlay_path = qc_dir / f"{Path(filename).stem}_qdf1_evo_edge_qc.jpg"
        write_rendered_qc_overlay(
            image_path=prepared.image_path,
            source_mask=prepared.source_mask,
            anchoring=fit.anchoring,
            template_cache=template_cache,
            output_path=overlay_path,
        )
        match = SliceEdgeRefineResult(
            filename=Path(filename).name,
            section_id=extract_section_id(filename),
            predicted_ap_mm=prepared.predicted_ap_mm,
            refined_ap_mm=fit.ap_mm,
            hint_ap_mm=float(prepared.hint.ap_mm) if prepared.hint is not None else None,
            hint_tolerance_mm=float(prepared.hint.tolerance_mm) if prepared.hint is not None else None,
            quicknii_y=fit.quicknii_y,
            score=float(fit.score),
            source_bbox=fit.source_bbox,
            atlas_bbox=fit.atlas_bbox,
            top_candidates=fit.top_candidates,
            roll_delta_deg=fit.roll_delta_deg,
            scale_factor=fit.scale_factor,
            original_deepslice_score=original_score,
            common_angle_score=common_angle_score,
            qc_overlay_path=overlay_path,
        )
        matches.append(match)
        logger.info(
            "QDF1 Evo refined %s: DeepSlice AP %.3f -> edge AP %.3f, score %.4f",
            filename,
            prepared.predicted_ap_mm,
            fit.ap_mm,
            fit.score,
        )

    refined_slices.sort(key=lambda item: -_safe_estimate_ap(item))
    for nr, item in enumerate(refined_slices, start=1):
        item["nr"] = nr
    payload["name"] = output_stem.stem
    payload["target"] = QDF1_EVO_TARGET
    payload["target-resolution"] = list(DEEPSLICE_MOUSE_QUICKNII_RESOLUTION)
    payload["slices"] = refined_slices

    refined_json = output_stem.with_suffix(".json")
    refined_csv = output_stem.with_suffix(".csv")
    refined_xml = output_stem.with_suffix(".xml")
    write_prediction_bundle(payload=payload, json_path=refined_json, csv_path=refined_csv, xml_path=refined_xml)
    report_path = output_stem.with_name(f"{output_stem.name}_edge_refine_report.csv")
    write_edge_refine_report(matches, report_path)
    if progress_callback:
        progress_callback("Writing refined JSON/CSV/XML", 1.0)
    return Qdf1EvoRunResult(
        input_dir=jpg_dir,
        jpg_dir=jpg_dir,
        baseline_json_path=json_path,
        refined_json_path=refined_json,
        refined_csv_path=refined_csv,
        refined_xml_path=refined_xml,
        report_path=report_path,
        qc_dir=qc_dir,
        matches=matches,
    )


def qdf1_anchoring_from_ccf_template(
    *,
    quicknii_y: int,
    source_width: int,
    source_height: int,
    source_bbox: tuple[int, int, int, int],
    atlas_bbox: tuple[int, int, int, int],
    atlas_shape: tuple[int, int],
    target_resolution: tuple[int, int, int] = DEEPSLICE_MOUSE_QUICKNII_RESOLUTION,
) -> list[float]:
    """Build QuickNII anchoring from a CCF coronal mask bbox alignment."""

    target_x, _, target_z = (float(value) for value in target_resolution)
    atlas_h, atlas_w = (float(value) for value in atlas_shape)
    sx0, sy0, sx1, sy1 = [float(value) for value in source_bbox]
    ax0, ay0, ax1, ay1 = [float(value) for value in atlas_bbox]
    sx_span = max(sx1 - sx0, 1.0)
    sy_span = max(sy1 - sy0, 1.0)

    def atlas_x_to_quicknii(x_value: float) -> float:
        scaled = x_value / max(atlas_w - 1.0, 1.0)
        return (target_x - 1.0) * (1.0 - scaled)

    def atlas_y_to_quicknii(y_value: float) -> float:
        scaled = y_value / max(atlas_h - 1.0, 1.0)
        return (target_z - 1.0) * (1.0 - scaled)

    left_x = atlas_x_to_quicknii(ax0)
    right_x = atlas_x_to_quicknii(ax1)
    top_z = atlas_y_to_quicknii(ay0)
    bottom_z = atlas_y_to_quicknii(ay1)
    u_x = (right_x - left_x) * float(source_width) / sx_span
    v_z = (bottom_z - top_z) * float(source_height) / sy_span
    origin_x = left_x - u_x * sx0 / max(float(source_width), 1.0)
    origin_z = top_z - v_z * sy0 / max(float(source_height), 1.0)
    return [
        float(origin_x),
        float(quicknii_y),
        float(origin_z),
        float(u_x),
        0.0,
        0.0,
        0.0,
        0.0,
        float(v_z),
    ]


def compare_prediction_to_teacher(
    *,
    prediction_json_path: Path,
    teacher_json_path: Path,
    output_path: Path,
) -> Path:
    """Compare a prediction JSON against a manually fitted teacher JSON."""

    prediction = json.loads(Path(prediction_json_path).read_text(encoding="utf-8"))
    teacher = json.loads(Path(teacher_json_path).read_text(encoding="utf-8"))
    predicted_by_name = {
        normalize_slice_lookup_key(str(item.get("filename", ""))): item
        for item in prediction.get("slices", [])
        if isinstance(item, dict)
    }
    rows: list[dict[str, object]] = []
    for teacher_slice in teacher.get("slices", []):
        if not isinstance(teacher_slice, dict):
            continue
        filename = Path(str(teacher_slice.get("filename", ""))).name
        key = normalize_slice_lookup_key(filename)
        predicted_slice = predicted_by_name.get(key)
        if predicted_slice is None:
            rows.append({"filename": filename, "matched": False})
            continue
        pred_ap = _safe_estimate_ap(predicted_slice)
        teacher_ap = _safe_estimate_ap(teacher_slice)
        pred_center = _anchoring_center(predicted_slice)
        teacher_center = _anchoring_center(teacher_slice)
        center_delta_vox = float(np.linalg.norm(pred_center - teacher_center))
        rows.append(
            {
                "filename": filename,
                "section_id": extract_section_id(filename),
                "matched": True,
                "predicted_ap_mm": pred_ap,
                "teacher_ap_mm": teacher_ap,
                "abs_ap_error_mm": abs(pred_ap - teacher_ap),
                "center_delta_vox": center_delta_vox,
                "center_delta_um": center_delta_vox * DEEPSLICE_MOUSE_VOXEL_SIZE_UM,
                "normal_angle_delta_deg": _normal_angle_delta_deg(predicted_slice, teacher_slice),
            }
        )
    frame = pd.DataFrame(rows)
    if not frame.empty and "abs_ap_error_mm" in frame.columns:
        summary = {
            "filename": "__SUMMARY__",
            "matched": bool(frame.get("matched", pd.Series(dtype=bool)).fillna(False).any()),
            "abs_ap_error_mm": float(pd.to_numeric(frame["abs_ap_error_mm"], errors="coerce").mean()),
            "center_delta_um": float(pd.to_numeric(frame["center_delta_um"], errors="coerce").mean()),
            "normal_angle_delta_deg": float(pd.to_numeric(frame["normal_angle_delta_deg"], errors="coerce").mean()),
        }
        frame = pd.concat([frame, pd.DataFrame([summary])], ignore_index=True)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(output_path, index=False)
    return output_path


def write_edge_refine_report(matches: list[SliceEdgeRefineResult], output_path: Path) -> Path:
    """Write per-section AP-limited edge-refinement diagnostics."""

    rows: list[dict[str, object]] = []
    for match in matches:
        rows.append(
            {
                "filename": match.filename,
                "section_id": match.section_id,
                "deepslice_ap_mm": match.predicted_ap_mm,
                "refined_ap_mm": match.refined_ap_mm,
                "hint_ap_mm": match.hint_ap_mm,
                "hint_tolerance_mm": match.hint_tolerance_mm,
                "quicknii_y": match.quicknii_y,
                "score": match.score,
                "original_deepslice_score": match.original_deepslice_score,
                "common_angle_score": match.common_angle_score,
                "fit_delta_vs_original": match.score - match.original_deepslice_score,
                "fit_delta_vs_common_angle": match.score - match.common_angle_score,
                "source_bbox_preview": ",".join(str(value) for value in match.source_bbox),
                "atlas_bbox_preview": ",".join(str(value) for value in match.atlas_bbox),
                "roll_delta_deg": match.roll_delta_deg,
                "scale_factor": match.scale_factor,
                "top_candidates": ";".join(f"y={y}:ap={ap:.3f}:score={score:.4f}" for y, ap, score in match.top_candidates),
                "qc_overlay": str(match.qc_overlay_path) if match.qc_overlay_path else "",
            }
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(output_path, index=False)
    return output_path


def write_ap_hints_from_teacher_json(
    *,
    teacher_json_path: Path,
    output_path: Path,
    tolerance_mm: float = 0.35,
) -> Path:
    """Create an AP hint CSV from a manually fitted teacher JSON."""

    payload = json.loads(Path(teacher_json_path).read_text(encoding="utf-8"))
    rows = []
    for item in payload.get("slices", []):
        if not isinstance(item, dict):
            continue
        filename = Path(str(item.get("filename", ""))).name
        if not filename:
            continue
        rows.append(
            {
                "slice_id_or_filename": filename,
                "section_id": extract_section_id(filename),
                "ap_mm": _safe_estimate_ap(item),
                "tolerance_mm": float(tolerance_mm),
            }
        )
    pd.DataFrame(rows).to_csv(output_path, index=False)
    return output_path


def write_rendered_qc_overlay(
    *,
    image_path: Path,
    source_mask: np.ndarray,
    anchoring: list[float],
    template_cache: CcfCoronalTemplateCache,
    output_path: Path,
) -> None:
    """Overlay the actually rendered refined-atlas contour on a section preview."""

    image = _read_grayscale_uint8(image_path)
    if image.size == 0:
        return
    image_preview, _ = _downsample_grayscale(image, max_side=DEFAULT_QC_MAX_SIDE)
    source_preview = _resize_nearest((source_mask > 0).astype(np.uint8), image_preview.shape[0], image_preview.shape[1])
    atlas_preview = _render_atlas_mask_from_anchoring(
        template_cache=template_cache,
        anchoring=anchoring,
        output_shape=image_preview.shape,
    )
    rgb = np.stack([image_preview, image_preview, image_preview], axis=-1)
    pil_image = Image.fromarray(rgb, mode="RGB")
    draw = ImageDraw.Draw(pil_image)
    _draw_mask_contours(draw, source_preview.astype(np.uint8), color=(0, 200, 255), width=2)
    _draw_mask_contours(draw, atlas_preview.astype(np.uint8), color=(255, 230, 0), width=3)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pil_image.save(output_path, quality=82, optimize=True)


def _constant_angle_slice_payloads(slices: list[dict[str, object]]) -> list[dict[str, object]]:
    """Return slice payloads whose anchoring vectors share one common angle."""

    anchors: list[np.ndarray] = []
    for item in slices:
        anchoring = np.asarray(item.get("anchoring", []), dtype=np.float64)
        if anchoring.size >= 9 and np.all(np.isfinite(anchoring[:9])):
            anchors.append(anchoring[:9])
    if not anchors:
        return [dict(item) for item in slices]

    ref_u = anchors[0][3:6]
    ref_v = anchors[0][6:9]
    unit_us: list[np.ndarray] = []
    unit_vs: list[np.ndarray] = []
    u_norms: list[float] = []
    v_norms: list[float] = []
    for anchoring in anchors:
        u = anchoring[3:6].astype(np.float64, copy=True)
        v = anchoring[6:9].astype(np.float64, copy=True)
        if float(np.dot(u, ref_u)) < 0.0:
            u *= -1.0
        if float(np.dot(v, ref_v)) < 0.0:
            v *= -1.0
        u_norm = float(np.linalg.norm(u))
        v_norm = float(np.linalg.norm(v))
        if u_norm > 1e-6 and v_norm > 1e-6:
            unit_us.append(u / u_norm)
            unit_vs.append(v / v_norm)
            u_norms.append(u_norm)
            v_norms.append(v_norm)
    if not unit_us or not unit_vs:
        return [dict(item) for item in slices]

    common_u_dir = _normalized_vector(np.mean(np.stack(unit_us, axis=0), axis=0), fallback=ref_u)
    common_v_raw = np.mean(np.stack(unit_vs, axis=0), axis=0)
    common_v_raw = common_v_raw - (common_u_dir * float(np.dot(common_v_raw, common_u_dir)))
    common_v_dir = _normalized_vector(common_v_raw, fallback=ref_v)
    median_u_norm = float(np.median(u_norms))
    median_v_norm = float(np.median(v_norms))
    common_u = common_u_dir * median_u_norm
    common_v = common_v_dir * median_v_norm

    outputs: list[dict[str, object]] = []
    for item in slices:
        anchoring = np.asarray(item.get("anchoring", []), dtype=np.float64)
        if anchoring.size < 9 or not np.all(np.isfinite(anchoring[:9])):
            outputs.append(dict(item))
            continue
        center = anchoring[0:3] + (0.5 * anchoring[3:6]) + (0.5 * anchoring[6:9])
        origin = center - (0.5 * common_u) - (0.5 * common_v)
        updated = dict(item)
        updated["anchoring"] = [float(value) for value in np.concatenate([origin, common_u, common_v])]
        updated["qdf1_evo_common_angle_source"] = "median_deepslice_orientation"
        outputs.append(updated)
    return outputs


def _estimate_global_roll_delta(
    *,
    prepared_slices: list[FitSlicePreparation],
    template_cache: CcfCoronalTemplateCache,
    ap_prior_weight: float,
) -> float:
    """Estimate one in-plane roll delta shared by the full slice series."""

    if not prepared_slices:
        return 0.0
    candidate_rolls = [-8.0, -4.0, 0.0, 4.0, 8.0]
    best_roll = 0.0
    best_score = -np.inf
    for roll_delta in candidate_rolls:
        slice_scores: list[float] = []
        for prepared in prepared_slices:
            baseline = np.asarray(prepared.constant_angle_slice.get("anchoring", []), dtype=np.float64)
            if baseline.size < 9:
                continue
            width = int(prepared.constant_angle_slice.get("width", prepared.fit_source_mask.shape[1]) or prepared.fit_source_mask.shape[1])
            height = int(prepared.constant_angle_slice.get("height", prepared.fit_source_mask.shape[0]) or prepared.fit_source_mask.shape[0])
            source_bbox = _mask_bbox(prepared.fit_source_mask)
            best_slice_score = -np.inf
            for y_value in _sample_candidate_y_values(prepared.candidate_y_values, max_count=7):
                anchoring = _anchoring_with_ap_roll_scale(
                    baseline=baseline,
                    target_y=float(y_value),
                    roll_delta_deg=float(roll_delta),
                    scale_factor=1.0,
                    image_width=width,
                    image_height=height,
                )
                score, _aligned, _atlas_bbox = _score_after_bbox_pan(
                    anchoring=anchoring,
                    source_mask=prepared.fit_source_mask,
                    source_bbox=source_bbox,
                    template_cache=template_cache,
                    prior_ap_mm=prepared.prior_ap_mm,
                    prior_width_mm=prepared.prior_width_mm,
                    ap_prior_weight=ap_prior_weight,
                    image_width=width,
                    image_height=height,
                )
                best_slice_score = max(best_slice_score, float(score))
            if math.isfinite(best_slice_score):
                slice_scores.append(best_slice_score)
        if slice_scores:
            mean_score = float(np.mean(slice_scores))
            if mean_score > best_score:
                best_score = mean_score
                best_roll = float(roll_delta)

    # Small refinement around the winning shared roll.
    refined_rolls = [best_roll - 2.0, best_roll - 1.0, best_roll, best_roll + 1.0, best_roll + 2.0]
    for roll_delta in refined_rolls:
        slice_scores = []
        for prepared in prepared_slices:
            baseline = np.asarray(prepared.constant_angle_slice.get("anchoring", []), dtype=np.float64)
            if baseline.size < 9:
                continue
            width = int(prepared.constant_angle_slice.get("width", prepared.fit_source_mask.shape[1]) or prepared.fit_source_mask.shape[1])
            height = int(prepared.constant_angle_slice.get("height", prepared.fit_source_mask.shape[0]) or prepared.fit_source_mask.shape[0])
            source_bbox = _mask_bbox(prepared.fit_source_mask)
            y_center = _sample_candidate_y_values(prepared.candidate_y_values, max_count=3)
            best_slice_score = -np.inf
            for y_value in y_center:
                anchoring = _anchoring_with_ap_roll_scale(
                    baseline=baseline,
                    target_y=float(y_value),
                    roll_delta_deg=float(roll_delta),
                    scale_factor=1.0,
                    image_width=width,
                    image_height=height,
                )
                score, _aligned, _atlas_bbox = _score_after_bbox_pan(
                    anchoring=anchoring,
                    source_mask=prepared.fit_source_mask,
                    source_bbox=source_bbox,
                    template_cache=template_cache,
                    prior_ap_mm=prepared.prior_ap_mm,
                    prior_width_mm=prepared.prior_width_mm,
                    ap_prior_weight=ap_prior_weight,
                    image_width=width,
                    image_height=height,
                )
                best_slice_score = max(best_slice_score, float(score))
            if math.isfinite(best_slice_score):
                slice_scores.append(best_slice_score)
        if slice_scores:
            mean_score = float(np.mean(slice_scores))
            if mean_score > best_score:
                best_score = mean_score
                best_roll = float(roll_delta)
    return best_roll


def _sample_candidate_y_values(values: list[int], *, max_count: int) -> list[int]:
    if len(values) <= max_count:
        return list(values)
    indices = np.linspace(0, len(values) - 1, num=max_count)
    sampled = sorted({int(values[int(round(index))]) for index in indices})
    center_index = len(values) // 2
    sampled.append(int(values[center_index]))
    return sorted(set(sampled))


def _normalized_vector(vector: np.ndarray, *, fallback: np.ndarray) -> np.ndarray:
    norm = float(np.linalg.norm(vector))
    if norm > 1e-8:
        return vector.astype(np.float64, copy=False) / norm
    fallback_norm = float(np.linalg.norm(fallback))
    if fallback_norm > 1e-8:
        return fallback.astype(np.float64, copy=False) / fallback_norm
    return np.array([1.0, 0.0, 0.0], dtype=np.float64)


def _fit_roll_primary_silhouette_to_source(
    *,
    baseline_slice: dict[str, object],
    target_y: int,
    template_cache: CcfCoronalTemplateCache,
    source_mask_preview: np.ndarray,
) -> AnchoringFit:
    """Final conservative fit: AP/scale/pan fixed, roll only."""

    baseline = np.asarray(baseline_slice.get("anchoring", []), dtype=np.float64)
    if baseline.size < 9 or not np.all(np.isfinite(baseline[:9])):
        raise ValueError(f"Slice {baseline_slice.get('filename')!r} does not have a valid DeepSlice anchoring.")
    width = int(baseline_slice.get("width", source_mask_preview.shape[1]) or source_mask_preview.shape[1])
    height = int(baseline_slice.get("height", source_mask_preview.shape[0]) or source_mask_preview.shape[0])
    source_bbox = _mask_bbox(source_mask_preview)

    fixed_scale = 1.0

    def score_candidate(roll_delta: float, dx_px: float, dy_px: float) -> tuple[float, list[float], tuple[int, int, int, int]]:
        anchoring = _anchoring_with_ap_roll_scale(
            baseline=baseline,
            target_y=float(target_y),
            roll_delta_deg=float(roll_delta),
            scale_factor=fixed_scale,
            image_width=width,
            image_height=height,
        )
        if dx_px or dy_px:
            anchoring = _translate_anchoring_by_preview_pixels(anchoring, dx_px, dy_px, source_mask_preview.shape)
            anchoring = _set_anchoring_center_y(anchoring, float(target_y))
        atlas_mask = _render_atlas_mask_from_anchoring(
            template_cache=template_cache,
            anchoring=anchoring,
            output_shape=source_mask_preview.shape,
        )
        atlas_bbox = _mask_bbox(atlas_mask)
        score = _score_rendered_overlay(
            source_mask=source_mask_preview,
            atlas_mask=atlas_mask,
            source_bbox=source_bbox,
            atlas_bbox=atlas_bbox,
        )
        return float(score), anchoring, atlas_bbox

    candidates: list[tuple[float, list[float], float, float, float, float, tuple[int, int, int, int]]] = []
    for roll_delta in [-8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0]:
        score, anchoring, atlas_bbox = score_candidate(roll_delta, 0.0, 0.0)
        candidates.append((score, anchoring, roll_delta, fixed_scale, 0.0, 0.0, atlas_bbox))

    candidates.sort(key=lambda row: row[0], reverse=True)
    for _score, _anchoring, roll_delta, scale_factor, dx_px, dy_px, _bbox in candidates[:5]:
        for fine_roll in [roll_delta - 1.0, roll_delta, roll_delta + 1.0]:
            score, anchoring, atlas_bbox = score_candidate(fine_roll, 0.0, 0.0)
            candidates.append((score, anchoring, fine_roll, fixed_scale, 0.0, 0.0, atlas_bbox))

    candidates.sort(key=lambda row: row[0], reverse=True)
    best_score, best_anchoring, best_roll, best_scale, _best_dx, _best_dy, best_atlas_bbox = candidates[0]
    top: list[tuple[int, float, float]] = []
    seen: set[tuple[int, int, int]] = set()
    for score, _anchoring, roll_delta, scale_factor, _dx, _dy, _bbox in candidates:
        key = (int(target_y), int(round(roll_delta * 10.0)), int(round(scale_factor * 1000.0)))
        if key in seen:
            continue
        seen.add(key)
        top.append((int(target_y), quicknii_y_to_ap_mm(target_y), float(score)))
        if len(top) >= 8:
            break
    final_ap = _estimate_ap_from_anchoring(best_anchoring, baseline_slice)
    return AnchoringFit(
        anchoring=[float(value) for value in best_anchoring],
        quicknii_y=int(target_y),
        ap_mm=float(final_ap if math.isfinite(final_ap) else quicknii_y_to_ap_mm(target_y)),
        score=float(best_score),
        source_bbox=source_bbox,
        atlas_bbox=best_atlas_bbox,
        top_candidates=top,
        roll_delta_deg=float(best_roll),
        scale_factor=float(best_scale),
    )


def _fit_real_rendered_atlas_to_source(
    *,
    baseline_slice: dict[str, object],
    candidate_y_values: list[int],
    template_cache: CcfCoronalTemplateCache,
    source_mask_preview: np.ndarray,
    prior_ap_mm: float,
    prior_width_mm: float,
    ap_prior_weight: float,
    fixed_roll_delta_deg: float | None = None,
    lock_center_y: bool = False,
) -> AnchoringFit:
    """Search AP/roll/scale/pan using real 3D atlas sampling from candidate anchoring."""

    baseline = np.asarray(baseline_slice.get("anchoring", []), dtype=np.float64)
    if baseline.size < 9 or not np.all(np.isfinite(baseline[:9])):
        raise ValueError(f"Slice {baseline_slice.get('filename')!r} does not have a valid DeepSlice anchoring.")
    width = int(baseline_slice.get("width", source_mask_preview.shape[1]) or source_mask_preview.shape[1])
    height = int(baseline_slice.get("height", source_mask_preview.shape[0]) or source_mask_preview.shape[0])
    source_bbox = _mask_bbox(source_mask_preview)

    scored: list[tuple[float, list[float], int, float, float, tuple[int, int, int, int]]] = []
    roll_values = [float(fixed_roll_delta_deg)] if fixed_roll_delta_deg is not None else [-8.0, -4.0, 0.0, 4.0, 8.0]
    for y_value in candidate_y_values:
        for roll_delta in roll_values:
            for scale_factor in [0.94, 1.0, 1.06]:
                anchoring = _anchoring_with_ap_roll_scale(
                    baseline=baseline,
                    target_y=float(y_value),
                    roll_delta_deg=roll_delta,
                    scale_factor=scale_factor,
                    image_width=width,
                    image_height=height,
                )
                score, aligned, atlas_bbox = _score_after_bbox_pan(
                    anchoring=anchoring,
                    source_mask=source_mask_preview,
                    source_bbox=source_bbox,
                    template_cache=template_cache,
                    prior_ap_mm=prior_ap_mm,
                    prior_width_mm=prior_width_mm,
                    ap_prior_weight=ap_prior_weight,
                    image_width=width,
                    image_height=height,
                    target_center_y=float(y_value) if lock_center_y else None,
                )
                scored.append((score, aligned, int(y_value), float(roll_delta), float(scale_factor), atlas_bbox))

    if not scored:
        raise RuntimeError("No rendered-atlas fit candidates were generated.")
    scored.sort(key=lambda row: row[0], reverse=True)
    refined: list[tuple[float, list[float], int, float, float, tuple[int, int, int, int]]] = scored[:8]
    extra_roll_values = [0.0] if fixed_roll_delta_deg is not None else [-2.0, 0.0, 2.0]
    for _seed_score, _seed_anchoring, y_value, roll_delta, scale_factor, _seed_bbox in scored[:4]:
        for extra_roll in extra_roll_values:
            for extra_scale in [0.98, 1.0, 1.02]:
                anchoring = _anchoring_with_ap_roll_scale(
                    baseline=baseline,
                    target_y=float(y_value),
                    roll_delta_deg=roll_delta + extra_roll,
                    scale_factor=scale_factor * extra_scale,
                    image_width=width,
                    image_height=height,
                )
                score, aligned, atlas_bbox = _score_after_bbox_pan(
                    anchoring=anchoring,
                    source_mask=source_mask_preview,
                    source_bbox=source_bbox,
                    template_cache=template_cache,
                    prior_ap_mm=prior_ap_mm,
                    prior_width_mm=prior_width_mm,
                    ap_prior_weight=ap_prior_weight,
                    image_width=width,
                    image_height=height,
                    target_center_y=float(y_value) if lock_center_y else None,
                )
                refined.append((score, aligned, int(y_value), float(roll_delta + extra_roll), float(scale_factor * extra_scale), atlas_bbox))
                for dx, dy in [(-18, 0), (18, 0), (0, -18), (0, 18), (-36, 0), (36, 0), (0, -36), (0, 36)]:
                    shifted = _translate_anchoring_by_preview_pixels(aligned, dx, dy, source_mask_preview.shape)
                    if lock_center_y:
                        shifted = _set_anchoring_center_y(shifted, float(y_value))
                    atlas_mask = _render_atlas_mask_from_anchoring(
                        template_cache=template_cache,
                        anchoring=shifted,
                        output_shape=source_mask_preview.shape,
                    )
                    atlas_bbox_shifted = _mask_bbox(atlas_mask)
                    shifted_score = _score_rendered_overlay(
                        source_mask=source_mask_preview,
                        atlas_mask=atlas_mask,
                        source_bbox=source_bbox,
                        atlas_bbox=atlas_bbox_shifted,
                    ) - _ap_prior_penalty(
                        anchoring=shifted,
                        baseline_slice=baseline_slice,
                        prior_ap_mm=prior_ap_mm,
                        prior_width_mm=prior_width_mm,
                        ap_prior_weight=ap_prior_weight,
                    )
                    refined.append(
                        (
                            float(shifted_score),
                            shifted,
                            int(y_value),
                            float(roll_delta + extra_roll),
                            float(scale_factor * extra_scale),
                            atlas_bbox_shifted,
                        )
                    )

    refined.sort(key=lambda row: row[0], reverse=True)
    best_score, best_anchoring, best_y, best_roll, best_scale, best_atlas_bbox = refined[0]
    top: list[tuple[int, float, float]] = []
    seen: set[tuple[int, int, int]] = set()
    for score, _anchoring, y_value, roll_delta, scale_factor, _bbox in refined:
        key = (int(y_value), int(round(roll_delta * 10.0)), int(round(scale_factor * 1000.0)))
        if key in seen:
            continue
        seen.add(key)
        top.append((int(y_value), quicknii_y_to_ap_mm(y_value), float(score)))
        if len(top) >= 8:
            break
    final_ap = _estimate_ap_from_anchoring(best_anchoring, baseline_slice)
    return AnchoringFit(
        anchoring=[float(value) for value in best_anchoring],
        quicknii_y=int(round(ap_mm_to_quicknii_y(final_ap))) if math.isfinite(final_ap) else int(best_y),
        ap_mm=float(final_ap if math.isfinite(final_ap) else quicknii_y_to_ap_mm(best_y)),
        score=float(best_score),
        source_bbox=source_bbox,
        atlas_bbox=best_atlas_bbox,
        top_candidates=top,
        roll_delta_deg=float(best_roll),
        scale_factor=float(best_scale),
    )


def _score_after_bbox_pan(
    *,
    anchoring: list[float],
    source_mask: np.ndarray,
    source_bbox: tuple[int, int, int, int],
    template_cache: CcfCoronalTemplateCache,
    prior_ap_mm: float,
    prior_width_mm: float,
    ap_prior_weight: float,
    image_width: int,
    image_height: int,
    target_center_y: float | None = None,
) -> tuple[float, list[float], tuple[int, int, int, int]]:
    atlas_mask = _render_atlas_mask_from_anchoring(
        template_cache=template_cache,
        anchoring=anchoring,
        output_shape=source_mask.shape,
    )
    aligned = _align_rendered_bbox_to_source_bbox(
        anchoring=anchoring,
        source_bbox=source_bbox,
        atlas_bbox=_mask_bbox(atlas_mask),
        preview_shape=source_mask.shape,
    )
    if target_center_y is not None:
        aligned = _set_anchoring_center_y(aligned, float(target_center_y))
    atlas_mask_aligned = _render_atlas_mask_from_anchoring(
        template_cache=template_cache,
        anchoring=aligned,
        output_shape=source_mask.shape,
    )
    atlas_bbox_aligned = _mask_bbox(atlas_mask_aligned)
    score = _score_rendered_overlay(
        source_mask=source_mask,
        atlas_mask=atlas_mask_aligned,
        source_bbox=source_bbox,
        atlas_bbox=atlas_bbox_aligned,
    ) - _ap_prior_penalty(
        anchoring=aligned,
        baseline_slice={"anchoring": aligned, "width": image_width, "height": image_height},
        prior_ap_mm=prior_ap_mm,
        prior_width_mm=prior_width_mm,
        ap_prior_weight=ap_prior_weight,
    )
    return float(score), aligned, atlas_bbox_aligned


def _score_slice_anchoring(
    *,
    anchoring: object,
    source_mask_preview: np.ndarray,
    template_cache: CcfCoronalTemplateCache,
) -> float:
    try:
        values = [float(value) for value in list(anchoring)]  # type: ignore[arg-type]
    except Exception:
        return float("nan")
    if len(values) < 9:
        return float("nan")
    source_bbox = _mask_bbox(source_mask_preview)
    atlas_mask = _render_atlas_mask_from_anchoring(
        template_cache=template_cache,
        anchoring=values,
        output_shape=source_mask_preview.shape,
    )
    return _score_rendered_overlay(
        source_mask=source_mask_preview,
        atlas_mask=atlas_mask,
        source_bbox=source_bbox,
        atlas_bbox=_mask_bbox(atlas_mask),
    )


def _anchoring_with_ap_roll_scale(
    *,
    baseline: np.ndarray,
    target_y: float,
    roll_delta_deg: float,
    scale_factor: float,
    image_width: int,
    image_height: int,
) -> list[float]:
    origin = baseline[0:3].astype(np.float64, copy=True)
    u = baseline[3:6].astype(np.float64, copy=True)
    v = baseline[6:9].astype(np.float64, copy=True)
    center = origin + (0.5 * u) + (0.5 * v)
    center[1] = float(target_y)
    width = max(float(image_width), 1.0)
    height = max(float(image_height), 1.0)
    theta = math.radians(float(roll_delta_deg))
    cos_t = math.cos(theta)
    sin_t = math.sin(theta)
    scaled_u = u * float(scale_factor)
    scaled_v = v * float(scale_factor)
    u_rot = (cos_t * scaled_u) + (sin_t * scaled_v * (width / height))
    v_rot = (-sin_t * scaled_u * (height / width)) + (cos_t * scaled_v)
    origin_new = center - (0.5 * u_rot) - (0.5 * v_rot)
    return [float(value) for value in np.concatenate([origin_new, u_rot, v_rot])]


def _align_rendered_bbox_to_source_bbox(
    *,
    anchoring: list[float],
    source_bbox: tuple[int, int, int, int],
    atlas_bbox: tuple[int, int, int, int],
    preview_shape: tuple[int, int],
) -> list[float]:
    sx0, sy0, sx1, sy1 = source_bbox
    ax0, ay0, ax1, ay1 = atlas_bbox
    source_cx = (sx0 + sx1) * 0.5
    source_cy = (sy0 + sy1) * 0.5
    atlas_cx = (ax0 + ax1) * 0.5
    atlas_cy = (ay0 + ay1) * 0.5
    return _translate_anchoring_by_preview_pixels(
        anchoring,
        dx_px=float(source_cx - atlas_cx),
        dy_px=float(source_cy - atlas_cy),
        preview_shape=preview_shape,
    )


def _set_anchoring_center_y(anchoring: list[float], target_y: float) -> list[float]:
    values = np.asarray(anchoring, dtype=np.float64).copy()
    if values.size < 9:
        return [float(value) for value in values]
    center_y = float(values[1] + (0.5 * values[4]) + (0.5 * values[7]))
    values[1] += float(target_y) - center_y
    return [float(value) for value in values]


def _translate_anchoring_by_preview_pixels(
    anchoring: list[float],
    dx_px: float,
    dy_px: float,
    preview_shape: tuple[int, int],
) -> list[float]:
    values = np.asarray(anchoring, dtype=np.float64).copy()
    h, w = preview_shape[:2]
    u = values[3:6]
    v = values[6:9]
    values[0:3] -= u * (float(dx_px) / max(float(w - 1), 1.0))
    values[0:3] -= v * (float(dy_px) / max(float(h - 1), 1.0))
    return [float(value) for value in values]


def _clean_one_jpg_for_deepslice(
    *,
    image_path: Path,
    slice_payload: dict[str, object] | None,
    output_dir: Path,
    qc_dir: Path,
    template_cache: CcfCoronalTemplateCache,
    preview_max_side: int,
    component_keep_fraction: float,
    min_atlas_keep_fraction: float,
    atlas_margin_fraction: float,
) -> CleanedJpgResult:
    gray = _read_grayscale_uint8(image_path)
    if gray.size == 0:
        raise ValueError(f"Could not read JPEG: {image_path}")
    preview, _scale = _downsample_grayscale(gray, max_side=preview_max_side)
    source_mask = tissue_mask_from_grayscale(preview)
    component_seed = _component_seed_mask_from_preview(preview)
    component_keep_seed, component_count_before, component_count_kept = _keep_large_tissue_components(
        component_seed,
        keep_fraction=component_keep_fraction,
    )
    component_keep_seed = _dilate_binary_mask(component_keep_seed, radius_px=4)
    component_mask = np.logical_and(source_mask > 0, component_keep_seed > 0).astype(np.uint8)
    component_mask = ndi.binary_fill_holes(component_mask > 0).astype(np.uint8)
    if int(component_mask.sum()) < int(source_mask.sum()) * 0.70:
        component_mask = source_mask
        component_count_before = 1
        component_count_kept = 1
    fallback_reason = ""
    atlas_mask = np.zeros_like(component_mask, dtype=np.uint8)
    final_keep = component_mask
    atlas_keep_fraction = float("nan")
    anchoring = slice_payload.get("anchoring", []) if slice_payload else []
    if isinstance(anchoring, list) and len(anchoring) >= 9 and int(component_mask.sum()) > 0:
        atlas_mask = _render_atlas_mask_from_anchoring(
            template_cache=template_cache,
            anchoring=[float(value) for value in anchoring[:9]],
            output_shape=preview.shape[:2],
        )
        atlas_mask = _clean_rendered_atlas_mask(atlas_mask)
        margin_px = max(12, int(round(max(preview.shape[:2]) * float(atlas_margin_fraction))))
        atlas_keep = _dilate_binary_mask(atlas_mask, radius_px=margin_px)
        combined = np.logical_and(component_mask > 0, atlas_keep > 0)
        component_area = int(component_mask.sum())
        combined_area = int(combined.sum())
        atlas_keep_fraction = float(combined_area) / max(float(component_area), 1.0)
        if combined_area <= 0 or atlas_keep_fraction < float(min_atlas_keep_fraction):
            fallback_reason = "atlas_mask_too_small_or_misaligned"
            final_keep = component_mask
        else:
            final_keep = combined.astype(np.uint8)
    else:
        fallback_reason = "no_valid_anchoring"

    full_keep = _resize_nearest(final_keep.astype(np.uint8), gray.shape[0], gray.shape[1])
    cleaned = gray.copy()
    cleaned[full_keep <= 0] = 0
    cleaned_path = output_dir / image_path.name
    Image.fromarray(cleaned).save(cleaned_path, quality=DEFAULT_CLEANUP_JPEG_QUALITY, optimize=True)

    qc_path = qc_dir / f"{image_path.stem}_cleanup_qc.jpg"
    _write_cleanup_qc_overlay(
        preview=preview,
        source_mask=source_mask,
        atlas_mask=atlas_mask,
        final_keep=final_keep,
        output_path=qc_path,
    )
    return CleanedJpgResult(
        filename=image_path.name,
        original_jpg=image_path,
        cleaned_jpg=cleaned_path,
        qc_overlay_path=qc_path,
        source_area_px=int(source_mask.sum()),
        component_area_px=int(component_mask.sum()),
        atlas_mask_area_px=int(atlas_mask.sum()),
        final_keep_area_px=int(final_keep.sum()),
        component_count_before=component_count_before,
        component_count_kept=component_count_kept,
        atlas_keep_fraction=atlas_keep_fraction,
        fallback_reason=fallback_reason,
    )


def _keep_large_tissue_components(mask: np.ndarray, *, keep_fraction: float) -> tuple[np.ndarray, int, int]:
    mask_bool = mask > 0
    labels, count = ndi.label(mask_bool)
    if count <= 1:
        return mask_bool.astype(np.uint8), int(count), int(count)
    areas = np.bincount(labels.ravel())
    component_areas = areas[1:]
    if component_areas.size == 0:
        return np.zeros_like(mask, dtype=np.uint8), int(count), 0
    largest_label = int(np.argmax(component_areas) + 1)
    largest_area = float(areas[largest_label])
    min_keep = max(largest_area * float(keep_fraction), float(mask.size) * 0.002)
    keep_labels = {largest_label}
    for label_index, area in enumerate(areas[1:], start=1):
        if float(area) >= min_keep:
            keep_labels.add(label_index)
    keep_mask = np.isin(labels, list(keep_labels))
    return keep_mask.astype(np.uint8), int(count), int(len(keep_labels))


def _component_seed_mask_from_preview(preview: np.ndarray) -> np.ndarray:
    """A less-filled mask used only to identify disconnected contaminating slices."""

    gray = preview.astype(np.float32, copy=False)
    if gray.size == 0 or float(np.max(gray)) <= 0.0:
        return np.zeros(gray.shape, dtype=np.uint8)
    sigma = max(1.5, float(min(gray.shape[:2])) / 140.0)
    blurred = ndi.gaussian_filter(gray, sigma=sigma)
    positive = blurred[blurred > 0]
    if positive.size == 0:
        return np.zeros(gray.shape, dtype=np.uint8)
    try:
        otsu_threshold = float(filters.threshold_otsu(blurred))
    except ValueError:
        otsu_threshold = float(np.percentile(positive, 50))
    floor_threshold = max(3.0, float(np.percentile(positive, 12)))
    threshold = max(floor_threshold, otsu_threshold * 0.65)
    mask = blurred >= threshold
    mask = ndi.binary_opening(mask, structure=np.ones((3, 3), dtype=bool), iterations=1)
    return mask.astype(np.uint8)


def _clean_rendered_atlas_mask(mask: np.ndarray) -> np.ndarray:
    mask_bool = mask > 0
    if not mask_bool.any():
        return np.zeros_like(mask, dtype=np.uint8)
    mask_bool = ndi.binary_closing(mask_bool, structure=np.ones((3, 3), dtype=bool), iterations=1)
    mask_bool = ndi.binary_fill_holes(mask_bool)
    return mask_bool.astype(np.uint8)


def _dilate_binary_mask(mask: np.ndarray, *, radius_px: int) -> np.ndarray:
    radius = max(1, int(radius_px))
    structure = morphology.disk(radius).astype(bool)
    return ndi.binary_dilation(mask > 0, structure=structure, iterations=1).astype(np.uint8)


def _write_cleanup_qc_overlay(
    *,
    preview: np.ndarray,
    source_mask: np.ndarray,
    atlas_mask: np.ndarray,
    final_keep: np.ndarray,
    output_path: Path,
) -> None:
    rgb = np.stack([preview, preview, preview], axis=-1).astype(np.uint8)
    outside = final_keep <= 0
    rgb[outside] = (rgb[outside].astype(np.float32) * 0.35).astype(np.uint8)
    overlay = Image.fromarray(rgb, mode="RGB")
    draw = ImageDraw.Draw(overlay)
    _draw_mask_contours(draw, source_mask, color=(0, 170, 255), width=1)
    if np.any(atlas_mask > 0):
        _draw_mask_contours(draw, atlas_mask, color=(255, 220, 0), width=2)
    _draw_mask_contours(draw, final_keep, color=(255, 40, 40), width=2)
    overlay.save(output_path, quality=90, optimize=True)


def write_cleanup_report(results: list[CleanedJpgResult], output_path: Path) -> None:
    rows = [
        {
            "filename": item.filename,
            "original_jpg": str(item.original_jpg),
            "cleaned_jpg": str(item.cleaned_jpg),
            "qc_overlay": str(item.qc_overlay_path),
            "source_area_px": item.source_area_px,
            "component_area_px": item.component_area_px,
            "atlas_mask_area_px": item.atlas_mask_area_px,
            "final_keep_area_px": item.final_keep_area_px,
            "component_count_before": item.component_count_before,
            "component_count_kept": item.component_count_kept,
            "atlas_keep_fraction": item.atlas_keep_fraction,
            "fallback_reason": item.fallback_reason,
        }
        for item in results
    ]
    pd.DataFrame(rows).to_csv(output_path, index=False)


def _write_runner_ap_hint_json_for_paths(
    *,
    image_paths: list[Path],
    hints: list[DeepSliceApHint],
    output_path: Path,
) -> Path:
    hint_lookup = build_ap_hint_lookup(hints)
    rows: list[dict[str, object]] = []
    for path in image_paths:
        path = Path(path)
        hint = hint_lookup.get(normalize_slice_lookup_key(path.name))
        section_id = extract_section_id(path.name)
        if hint is None and section_id:
            hint = hint_lookup.get(section_id.lower())
        if hint is None:
            continue
        rows.append(
            {
                "filename": path.name,
                "section_id": section_id,
                "ap_mm": float(hint.ap_mm),
                "tolerance_mm": float(hint.tolerance_mm),
            }
        )
    output_path.write_text(json.dumps({"hints": rows}, ensure_ascii=False, indent=2), encoding="utf-8")
    return output_path


def _render_atlas_mask_from_anchoring(
    *,
    template_cache: CcfCoronalTemplateCache,
    anchoring: list[float],
    output_shape: tuple[int, int],
) -> np.ndarray:
    labels = template_cache.labels
    values = np.asarray(anchoring, dtype=np.float64)
    if values.size < 9:
        return np.zeros(output_shape[:2], dtype=np.uint8)
    h, w = int(output_shape[0]), int(output_shape[1])
    yy, xx = np.mgrid[0:h, 0:w]
    x_norm = xx.astype(np.float64) / max(float(w - 1), 1.0)
    y_norm = yy.astype(np.float64) / max(float(h - 1), 1.0)
    coords = values[0:3] + (x_norm[..., None] * values[3:6]) + (y_norm[..., None] * values[6:9])
    rounded = np.rint(coords).astype(np.int32, copy=False)
    valid = (
        (rounded[..., 0] >= 0)
        & (rounded[..., 0] < labels.shape[0])
        & (rounded[..., 1] >= 0)
        & (rounded[..., 1] < labels.shape[1])
        & (rounded[..., 2] >= 0)
        & (rounded[..., 2] < labels.shape[2])
    )
    mask = np.zeros((h, w), dtype=np.uint8)
    if np.any(valid):
        sampled = labels[
            rounded[..., 0][valid],
            rounded[..., 1][valid],
            rounded[..., 2][valid],
        ]
        mask[valid] = (sampled > 0).astype(np.uint8)
    return mask


def _score_rendered_overlay(
    *,
    source_mask: np.ndarray,
    atlas_mask: np.ndarray,
    source_bbox: tuple[int, int, int, int],
    atlas_bbox: tuple[int, int, int, int],
) -> float:
    source_bool = source_mask > 0
    atlas_bool = atlas_mask > 0
    union = np.logical_or(source_bool, atlas_bool).sum()
    if union == 0:
        return -1.0
    intersection = np.logical_and(source_bool, atlas_bool).sum()
    iou = float(intersection) / float(union)
    source_edge = feature.canny(source_bool, sigma=1.0)
    atlas_edge = feature.canny(atlas_bool, sigma=1.0)
    chamfer_terms: list[float] = []
    if source_edge.any() and atlas_edge.any():
        atlas_dist = ndi.distance_transform_edt(~atlas_edge)
        source_dist = ndi.distance_transform_edt(~source_edge)
        norm = float(max(source_mask.shape[:2]))
        chamfer_terms.append(float(np.mean(atlas_dist[source_edge])) / max(norm, 1.0))
        chamfer_terms.append(float(np.mean(source_dist[atlas_edge])) / max(norm, 1.0))
    chamfer = float(np.mean(chamfer_terms)) if chamfer_terms else 1.0
    sx0, sy0, sx1, sy1 = source_bbox
    ax0, ay0, ax1, ay1 = atlas_bbox
    source_aspect = max(sx1 - sx0, 1) / max(sy1 - sy0, 1)
    atlas_aspect = max(ax1 - ax0, 1) / max(ay1 - ay0, 1)
    aspect_penalty = min(abs(math.log(max(source_aspect, 1e-6) / max(atlas_aspect, 1e-6))), 1.0)
    source_area = max(float(source_bool.sum()), 1.0)
    atlas_area = max(float(atlas_bool.sum()), 1.0)
    area_penalty = min(abs(math.log(source_area / atlas_area)), 1.0)
    return (0.62 * iou) + (0.34 * (1.0 - min(chamfer, 1.0))) - (0.05 * aspect_penalty) - (0.05 * area_penalty)


def _ap_prior_penalty(
    *,
    anchoring: list[float],
    baseline_slice: dict[str, object],
    prior_ap_mm: float,
    prior_width_mm: float,
    ap_prior_weight: float,
) -> float:
    ap_value = _estimate_ap_from_anchoring(anchoring, baseline_slice)
    if not math.isfinite(ap_value):
        return 0.0
    width = max(float(prior_width_mm), DEEPSLICE_MOUSE_VOXEL_SIZE_UM / 1000.0)
    return float(ap_prior_weight) * min(abs(ap_value - float(prior_ap_mm)) / width, 1.0)


def _estimate_ap_from_anchoring(anchoring: list[float], baseline_slice: dict[str, object]) -> float:
    payload = dict(baseline_slice)
    payload["anchoring"] = [float(value) for value in anchoring]
    return _safe_estimate_ap(payload)


def _downsample_binary_mask(mask: np.ndarray, *, max_side: int) -> tuple[np.ndarray, float]:
    h, w = mask.shape[:2]
    scale = min(1.0, float(max_side) / max(float(max(h, w)), 1.0))
    if scale >= 1.0:
        return (mask > 0).astype(np.uint8), 1.0
    new_h = max(1, int(round(h * scale)))
    new_w = max(1, int(round(w * scale)))
    resized = transform.resize(
        (mask > 0).astype(np.uint8),
        (new_h, new_w),
        order=0,
        mode="edge",
        preserve_range=True,
        anti_aliasing=False,
    )
    return (resized > 0.5).astype(np.uint8), scale


def _downsample_grayscale(image: np.ndarray, *, max_side: int) -> tuple[np.ndarray, float]:
    h, w = image.shape[:2]
    scale = min(1.0, float(max_side) / max(float(max(h, w)), 1.0))
    if scale >= 1.0:
        return image.astype(np.uint8, copy=False), 1.0
    new_h = max(1, int(round(h * scale)))
    new_w = max(1, int(round(w * scale)))
    resized = transform.resize(
        image.astype(np.float32, copy=False),
        (new_h, new_w),
        order=1,
        mode="edge",
        preserve_range=True,
        anti_aliasing=True,
    )
    return np.clip(resized, 0, 255).astype(np.uint8), scale


def quicknii_y_to_ap_mm(quicknii_y: float) -> float:
    """Convert QuickNII AP-axis voxel coordinate to bregma AP millimeters."""

    allen_x_um = (float(DEEPSLICE_MOUSE_QUICKNII_RESOLUTION[1] - 1) - float(quicknii_y)) * DEEPSLICE_MOUSE_VOXEL_SIZE_UM
    ap_um = DEEPSLICE_MOUSE_BREGMA_UM[0] - allen_x_um
    return float(ap_um / 1000.0)


def ap_mm_to_quicknii_y(ap_mm: float) -> float:
    """Convert bregma AP millimeters to QuickNII AP-axis voxel coordinate."""

    allen_x_um = DEEPSLICE_MOUSE_BREGMA_UM[0] - (float(ap_mm) * 1000.0)
    return float(DEEPSLICE_MOUSE_QUICKNII_RESOLUTION[1] - 1) - (allen_x_um / DEEPSLICE_MOUSE_VOXEL_SIZE_UM)


def _best_template_for_source(
    *,
    source_signature: np.ndarray,
    source_bbox: tuple[int, int, int, int],
    candidate_y_values: list[int],
    template_cache: CcfCoronalTemplateCache,
    prior_ap_mm: float,
    prior_width_mm: float,
    ap_prior_weight: float,
) -> tuple[CcfCoronalTemplate, float, list[tuple[int, float, float]]]:
    scored: list[tuple[CcfCoronalTemplate, float]] = []
    for y_value in candidate_y_values:
        template = template_cache.template(y_value)
        edge_score = _score_mask_signature(
            source_signature=source_signature,
            source_bbox=source_bbox,
            atlas_signature=template.signature,
            atlas_bbox=template.bbox,
        )
        prior_width = max(float(prior_width_mm), DEEPSLICE_MOUSE_VOXEL_SIZE_UM / 1000.0)
        prior_penalty = min(abs(float(template.ap_mm) - float(prior_ap_mm)) / prior_width, 1.0)
        score = float(edge_score) - (float(ap_prior_weight) * prior_penalty)
        scored.append((template, score))
    if not scored:
        raise RuntimeError("No atlas templates were available for edge refinement.")
    scored.sort(key=lambda row: row[1], reverse=True)
    top = [(item.quicknii_y, item.ap_mm, score) for item, score in scored[:8]]
    return scored[0][0], scored[0][1], top


def _candidate_y_values(
    *,
    predicted_ap_mm: float,
    hint: DeepSliceApHint | None,
    no_hint_search_mm: float,
    ap_step_vox: int,
    max_y: int,
) -> tuple[list[int], float, float]:
    if hint is not None:
        prior_ap = float(hint.ap_mm)
        prior_width_mm = max(float(hint.tolerance_mm), DEEPSLICE_MOUSE_VOXEL_SIZE_UM / 1000.0)
        center_y = ap_mm_to_quicknii_y(prior_ap)
        half_width = max(1, int(math.ceil((prior_width_mm * 1000.0) / DEEPSLICE_MOUSE_VOXEL_SIZE_UM)))
    else:
        prior_ap = predicted_ap_mm if math.isfinite(predicted_ap_mm) else 0.0
        prior_width_mm = max(float(no_hint_search_mm), DEEPSLICE_MOUSE_VOXEL_SIZE_UM / 1000.0)
        center_y = ap_mm_to_quicknii_y(prior_ap)
        half_width = max(1, int(math.ceil((prior_width_mm * 1000.0) / DEEPSLICE_MOUSE_VOXEL_SIZE_UM)))
    center = int(round(center_y))
    step = max(1, int(ap_step_vox))
    start = max(0, center - half_width)
    stop = min(int(max_y), center + half_width)
    values = list(range(start, stop + 1, step))
    center_clamped = int(np.clip(center, 0, max_y))
    if center_clamped not in values:
        values.append(center_clamped)
        values.sort()
    return values, prior_ap, prior_width_mm


def _hint_for_slice(filename: str, hint_lookup: dict[str, DeepSliceApHint]) -> DeepSliceApHint | None:
    section_id = extract_section_id(filename)
    return hint_lookup.get(normalize_slice_lookup_key(filename)) or (hint_lookup.get(section_id.lower()) if section_id else None)


def _safe_estimate_ap(slice_payload: dict[str, object]) -> float:
    try:
        return float(estimate_slice_ap_mm(slice_payload, species="mouse"))
    except Exception:
        return float("nan")


def _anchoring_center(slice_payload: dict[str, object]) -> np.ndarray:
    width = float(slice_payload.get("width", 0) or 0)
    height = float(slice_payload.get("height", 0) or 0)
    # Width/height are intentionally unused because QuickNII anchoring stores
    # full image span vectors, matching estimate_slice_ap_mm.
    _ = (width, height)
    anchoring = np.asarray(slice_payload.get("anchoring", []), dtype=np.float64)
    if anchoring.size < 9:
        return np.full(3, np.nan, dtype=np.float64)
    return anchoring[0:3] + (anchoring[3:6] * 0.5) + (anchoring[6:9] * 0.5)


def _normal_angle_delta_deg(a_slice: dict[str, object], b_slice: dict[str, object]) -> float:
    a = np.asarray(a_slice.get("anchoring", []), dtype=np.float64)
    b = np.asarray(b_slice.get("anchoring", []), dtype=np.float64)
    if a.size < 9 or b.size < 9:
        return float("nan")
    a_normal = np.cross(a[3:6], a[6:9])
    b_normal = np.cross(b[3:6], b[6:9])
    a_norm = float(np.linalg.norm(a_normal))
    b_norm = float(np.linalg.norm(b_normal))
    if a_norm <= 0.0 or b_norm <= 0.0:
        return float("nan")
    cosine = float(np.clip(np.dot(a_normal, b_normal) / (a_norm * b_norm), -1.0, 1.0))
    return float(math.degrees(math.acos(cosine)))


def _clean_template_mask(mask: np.ndarray) -> np.ndarray:
    # CCF background can contain narrow holes at ventricles/tract boundaries; for
    # AP plane selection we need the outer brain silhouette rather than labels.
    from scipy import ndimage as ndi

    mask_bool = mask > 0
    mask_bool = ndi.binary_closing(mask_bool, structure=np.ones((3, 3), dtype=bool), iterations=1)
    mask_bool = ndi.binary_fill_holes(mask_bool)
    return mask_bool.astype(np.uint8)


def _default_atlas_root() -> Path:
    bundle_root = Path(__file__).resolve().parents[2]
    candidates = [
        bundle_root / "atlas" / "ccf",
        bundle_root.parent / "atlas" / "ccf",
        Path.home() / "Documents" / "QDF_portable" / "atlas" / "ccf",
    ]
    for candidate in candidates:
        if (candidate / "annotation_25.nrrd").exists():
            return candidate.resolve()
    raise FileNotFoundError("annotation_25.nrrd was not found for QDF1 Evo edge refinement.")


def _scaled_progress(
    callback: Callable[[str, float], None] | None,
    start: float,
    end: float,
) -> Callable[[str, float], None] | None:
    if callback is None:
        return None

    def scaled(message: str, fraction: float) -> None:
        value = start + ((end - start) * max(0.0, min(float(fraction), 1.0)))
        callback(message, value)

    return scaled


def main(argv: list[str] | None = None) -> int:
    """Small CLI for smoke tests and teacher-based validation."""

    import argparse

    parser = argparse.ArgumentParser(description="Refine a QDF1 DeepSlice JSON using AP-limited CCF edge matching.")
    parser.add_argument("--json", type=Path, required=True, help="Baseline DeepSlice JSON.")
    parser.add_argument("--jpg-dir", type=Path, default=None, help="Directory containing slice JPEGs.")
    parser.add_argument("--ap-hints", type=Path, default=None, help="AP hint CSV/TSV/XLSX.")
    parser.add_argument("--teacher-json", type=Path, default=None, help="Optional manual teacher JSON for metrics.")
    parser.add_argument("--output-stem", type=Path, default=None, help="Output stem for refined JSON/CSV/XML.")
    parser.add_argument("--make-hints-from-teacher", action="store_true", help="Write AP hints from teacher JSON and exit.")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    if args.make_hints_from_teacher:
        if args.teacher_json is None:
            raise SystemExit("--teacher-json is required with --make-hints-from-teacher")
        output = args.ap_hints or args.teacher_json.with_name(f"{args.teacher_json.stem}_ap_hints.csv")
        write_ap_hints_from_teacher_json(teacher_json_path=args.teacher_json, output_path=output)
        print(output)
        return 0
    result = refine_deepslice_prediction_json(
        json_path=args.json,
        jpg_dir=args.jpg_dir,
        output_stem=args.output_stem,
        ap_hint_path=args.ap_hints,
        progress_callback=lambda message, fraction: print(f"{fraction:5.1%} {message}"),
        logger=LOG,
    )
    if args.teacher_json:
        metrics = compare_prediction_to_teacher(
            prediction_json_path=result.refined_json_path,
            teacher_json_path=args.teacher_json,
            output_path=result.refined_json_path.with_name(f"{result.refined_json_path.stem}_teacher_metrics.csv"),
        )
        print(metrics)
    print(result.refined_json_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
