"""Prepare JPEGs and run DeepSlice predictions for one image directory."""

from __future__ import annotations

from dataclasses import dataclass
import io
import json
import logging
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Callable
import xml.etree.ElementTree as ET

import numpy as np
import pandas as pd
from PIL import Image, ImageFilter, ImageOps
import tifffile

try:
    from skimage import exposure
except Exception:  # pragma: no cover - optional fallback
    exposure = None

from io_utils.discovery import extract_image_channel

LOG = logging.getLogger(__name__)

DEFAULT_DEEPSLICE_PYTHON = Path("deepslice_env") / "python.exe"
PRIMARY_DEEPSLICE_ENV_VAR = "QUINTDEEPFLOW_DEEPSLICE_PYTHON"
LEGACY_DEEPSLICE_ENV_VARS = (
    "QUINTDEEPFLOW2_DEEPSLICE_PYTHON",
    "QUINTFLOW2_DEEPSLICE_PYTHON",
)
PORTABLE_DEEPSLICE_PYTHON = Path("portable_runtime") / "deepslice_env" / "python.exe"
DEFAULT_JPEG_QUALITY = 78
MIN_JPEG_QUALITY = 52
TARGET_JPEG_BYTES = 3_500_000
DEFAULT_AP_TOLERANCE_MM = 0.35
DEEPSLICE_MOUSE_VOXEL_SIZE_UM = 25.0
DEEPSLICE_MOUSE_QUICKNII_RESOLUTION = (456, 528, 320)
DEEPSLICE_MOUSE_BREGMA_UM = (5400.0, 0.0, 5700.0)
SECTION_ID_PATTERN = re.compile(r"(XY\d+)", re.IGNORECASE)


@dataclass(slots=True)
class ConvertedJpg:
    """One TIFF converted to a DeepSlice-ready JPEG."""

    source_tiff: Path
    output_jpg: Path
    enhanced: bool
    source_min: float
    source_max: float
    source_p99_5: float
    jpeg_quality: int
    file_size_bytes: int


@dataclass(slots=True)
class DeepSliceApHint:
    """User-provided rough AP prior for one section."""

    filename_stem: str | None
    section_id: str | None
    ap_mm: float
    tolerance_mm: float
    order_index: int


@dataclass(slots=True)
class DeepSliceRunResult:
    """Artifacts generated by one DeepSlice run."""

    input_dir: Path
    jpg_dir: Path
    output_stem: Path
    json_path: Path
    csv_path: Path
    xml_path: Path
    selected_channel: str
    deepslice_python: Path
    converted_images: list[ConvertedJpg]
    same_slicing_angle: bool
    ap_hint_path: Path | None
    ap_hint_mode: str
    ap_hint_report_path: Path | None = None
    reran_with_ap_hint_order: bool = False


def run_deepslice_job(
    input_dir: Path,
    channel: str,
    *,
    progress_callback: Callable[[str, float], None] | None = None,
    logger: logging.Logger | None = None,
    deepslice_python: Path | None = None,
    species: str = "mouse",
    use_ensemble: bool = True,
    same_slicing_angle: bool = False,
    ap_hint_path: Path | None = None,
    ap_hint_mode: str = "disabled",
    constrain_deepslice_to_ap_hints: bool = False,
    output_stem_name: str = "jpgDS_results",
    ap_hint_report_name: str = "jpgDS_ap_hint_report.csv",
) -> DeepSliceRunResult:
    """Convert one channel to JPEG and run DeepSlice against the created JPEG set."""

    logger = logger or LOG
    channel = channel.strip().upper()
    if not channel:
        raise ValueError("Channel is required.")

    input_dir = input_dir.resolve()
    if not input_dir.exists():
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")

    normalized_hint_mode = normalize_ap_hint_mode(ap_hint_mode)
    ap_hint_file = Path(ap_hint_path).resolve() if ap_hint_path and str(ap_hint_path).strip() else None
    ap_hints = load_ap_position_hints(ap_hint_file) if ap_hint_file else []
    if ap_hints and species.lower() != "mouse":
        raise ValueError("AP hint post-processing is currently supported for mouse DeepSlice outputs only.")

    if progress_callback:
        progress_callback("Scanning TIFF files", 0.05)
    tiff_paths = discover_channel_tiffs(input_dir, channel)
    if not tiff_paths:
        raise FileNotFoundError(f"No TIFF files for {channel} found in: {input_dir}")

    jpg_dir = derive_jpg_dir(input_dir)
    jpg_dir.mkdir(parents=True, exist_ok=True)
    logger.info("DeepSlice JPEG output directory: %s", jpg_dir)
    remove_legacy_quicknii_artifacts(jpg_dir, logger=logger)

    if progress_callback:
        progress_callback("Converting TIFF to JPEG", 0.20)
    converted = convert_tiffs_to_jpgs(tiff_paths, jpg_dir, logger=logger)
    auxiliary_converted = convert_nonselected_channel_tiffs_to_jpgs(
        input_dir=input_dir,
        selected_channel=channel,
        jpg_dir=jpg_dir,
        logger=logger,
    )
    if auxiliary_converted:
        logger.info(
            "Prepared %d non-fitting channel JPEG(s) for AtlasFitter display.",
            len(auxiliary_converted),
        )

    output_name = Path(str(output_stem_name).strip() or "jpgDS_results").stem
    output_stem = jpg_dir / output_name
    runner_script = Path(__file__).resolve().parents[1] / "tools" / "deepslice_predict_runner.py"
    python_path = resolve_deepslice_python(deepslice_python)

    manifest_entries = [item.output_jpg for item in converted]
    reran_with_ap_hint_order = False
    if ap_hints and normalized_hint_mode == "guided":
        guided_manifest = build_ap_guided_manifest(converted, ap_hints)
        if guided_manifest is not None:
            manifest_entries = guided_manifest
            reran_with_ap_hint_order = True
            logger.info("Using AP-guided slice order for the initial DeepSlice run")
        else:
            logger.warning(
                "AP-guided order was skipped because the hint file does not cover every converted slice."
            )

    if progress_callback:
        progress_callback("Running DeepSlice", 0.52)
    runner_ap_hint_path = None
    if ap_hints and constrain_deepslice_to_ap_hints:
        runner_ap_hint_path = write_runner_ap_hint_json(
            converted=converted,
            hints=ap_hints,
            output_path=output_stem.parent / f".deepslice_ap_hints_{channel.lower()}.json",
        )
        logger.info("Using AP-constrained DeepSlice prediction: %s", runner_ap_hint_path)
    run_deepslice_predictions(
        manifest_paths=manifest_entries,
        output_stem=output_stem,
        python_executable=python_path,
        runner_script=runner_script,
        species=species,
        use_ensemble=use_ensemble,
        same_slicing_angle=same_slicing_angle,
        logger=logger,
        manifest_channel=channel,
        ap_hint_json_path=runner_ap_hint_path,
    )

    json_path = output_stem.with_suffix(".json")
    csv_path = output_stem.with_suffix(".csv")
    xml_path = output_stem.with_suffix(".xml")
    normalize_prediction_outputs(
        json_path=json_path,
        csv_path=csv_path,
        xml_path=xml_path,
    )

    ap_hint_report_path: Path | None = None

    if ap_hints:
        if progress_callback:
            progress_callback("Checking AP hints", 0.76)
        report_frame = build_ap_hint_report(
            json_path=json_path,
            hints=ap_hints,
            species=species,
        )
        outlier_count = int(report_frame["outside_tolerance"].sum()) if not report_frame.empty else 0
        logger.info("AP hint check matched %d slices (%d outside tolerance)", len(report_frame), outlier_count)

        if normalized_hint_mode == "guided" and outlier_count > 0:
            if progress_callback:
                progress_callback("Rewriting out-of-range slices to AP hints", 0.84)
            report_frame = rewrite_predictions_to_ap_hints(
                json_path=json_path,
                csv_path=csv_path,
                xml_path=xml_path,
                hints=ap_hints,
                species=species,
                logger=logger,
            )

        report_name = Path(str(ap_hint_report_name).strip() or "jpgDS_ap_hint_report.csv").name
        ap_hint_report_path = output_stem.parent / report_name
        report_frame.to_csv(ap_hint_report_path, index=False)
        logger.info("AP hint report written: %s", ap_hint_report_path)

    if progress_callback:
        progress_callback("Done", 1.0)

    return DeepSliceRunResult(
        input_dir=input_dir,
        jpg_dir=jpg_dir,
        output_stem=output_stem,
        json_path=json_path,
        csv_path=csv_path,
        xml_path=xml_path,
        selected_channel=channel,
        deepslice_python=python_path,
        converted_images=converted,
        same_slicing_angle=bool(same_slicing_angle),
        ap_hint_path=ap_hint_file,
        ap_hint_mode=normalized_hint_mode,
        ap_hint_report_path=ap_hint_report_path,
        reran_with_ap_hint_order=reran_with_ap_hint_order,
    )


def derive_jpg_dir(input_dir: Path) -> Path:
    """Create a sibling `jpg` directory next to the selected TIFF directory."""

    if input_dir.name.lower() == "jpg":
        return input_dir
    return input_dir.parent / "jpg"


def discover_channel_tiffs(input_dir: Path, channel: str) -> list[Path]:
    """Return TIFF files in the directory that belong to the selected channel."""

    matched: list[Path] = []
    for path in sorted(input_dir.iterdir()):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".tif", ".tiff"}:
            continue
        if extract_image_channel(path.name).upper() != channel.upper():
            continue
        matched.append(path)
    return matched


def discover_nonselected_channel_tiffs(input_dir: Path, selected_channel: str) -> list[Path]:
    """Return TIFF files for channels other than the fitting channel."""

    selected = selected_channel.strip().upper()
    matched: list[Path] = []
    for path in sorted(input_dir.iterdir()):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".tif", ".tiff"}:
            continue
        image_channel = extract_image_channel(path.name).upper()
        if not image_channel or image_channel == selected:
            continue
        matched.append(path)
    return matched


def convert_nonselected_channel_tiffs_to_jpgs(
    input_dir: Path,
    selected_channel: str,
    jpg_dir: Path,
    *,
    logger: logging.Logger | None = None,
) -> list[ConvertedJpg]:
    """Write contrast-enhanced JPEGs for non-fitting channels without using them for DeepSlice."""

    other_tiffs = discover_nonselected_channel_tiffs(input_dir, selected_channel)
    if not other_tiffs:
        return []
    logger = logger or LOG
    logger.info(
        "Preparing display JPEGs for %d non-fitting channel TIFF(s).",
        len(other_tiffs),
    )
    return convert_tiffs_to_jpgs(other_tiffs, jpg_dir, logger=logger)


def normalize_ap_hint_mode(value: str | None) -> str:
    """Map GUI labels and raw strings to stable internal AP-hint modes."""

    normalized = (value or "").strip().lower()
    if normalized in {"", "disabled", "off", "none"}:
        return "disabled"
    if normalized in {
        "rerun",
        "rerun if ap deviates",
        "rerun_if_outside_tolerance",
        "rewrite",
        "rewrite result to ap hint",
        "rewrite_to_ap_hint",
        "use ap hint order + rewrite if needed",
        "guided",
    }:
        return "guided"
    raise ValueError(f"Unsupported AP hint mode: {value}")


def load_ap_position_hints(path: Path) -> list[DeepSliceApHint]:
    """Load section-level AP priors from CSV/TSV/XLSX."""

    suffix = path.suffix.lower()
    if suffix in {".xlsx", ".xls"}:
        frame = pd.read_excel(path)
    elif suffix in {".tsv", ".txt"}:
        frame = pd.read_csv(path, sep="\t")
    else:
        frame = pd.read_csv(path)

    normalized_columns = {str(column).strip().lower(): column for column in frame.columns}

    def require_column(candidates: tuple[str, ...]) -> str:
        for candidate in candidates:
            if candidate in normalized_columns:
                return normalized_columns[candidate]
        raise ValueError(f"{path} must contain one of the columns: {', '.join(candidates)}")

    def optional_column(candidates: tuple[str, ...]) -> str | None:
        for candidate in candidates:
            if candidate in normalized_columns:
                return normalized_columns[candidate]
        return None

    ap_column = require_column(("ap_mm", "ap", "ap_position_mm", "approx_ap_mm"))
    tolerance_column = optional_column(("tolerance_mm", "tolerance", "allowed_error_mm"))
    slice_key_column = optional_column(("slice_id_or_filename", "slice_key", "slice_identifier"))
    filename_column = optional_column(("filename", "file", "image", "image_file"))
    section_column = optional_column(("section_id", "section", "slice_id", "slice"))

    if slice_key_column is None and filename_column is None and section_column is None:
        raise ValueError(f"{path} must contain either a filename or section_id column.")

    hints: list[DeepSliceApHint] = []
    for row_index, row in frame.iterrows():
        raw_ap = row.get(ap_column)
        if pd.isna(raw_ap):
            continue
        filename_stem = None
        slice_key = None
        if slice_key_column is not None and not pd.isna(row.get(slice_key_column)):
            slice_key = str(row[slice_key_column]).strip()
            if slice_key:
                filename_stem = Path(slice_key).stem.lower()
        if filename_column is not None and not pd.isna(row.get(filename_column)):
            filename_stem = Path(str(row[filename_column]).strip()).stem.lower()
        section_id = None
        if slice_key:
            section_id = extract_section_id(slice_key)
        if section_column is not None and not pd.isna(row.get(section_column)):
            section_id = str(row[section_column]).strip().upper()
        tolerance_value = DEFAULT_AP_TOLERANCE_MM
        if tolerance_column is not None and not pd.isna(row.get(tolerance_column)):
            tolerance_value = float(row[tolerance_column])
        hints.append(
            DeepSliceApHint(
                filename_stem=filename_stem,
                section_id=section_id,
                ap_mm=float(raw_ap),
                tolerance_mm=max(float(tolerance_value), 0.0),
                order_index=int(row_index),
            )
        )
    if not hints:
        raise ValueError(f"No valid AP hint rows found in: {path}")
    return hints


def remove_legacy_quicknii_artifacts(jpg_dir: Path, *, logger: logging.Logger | None = None) -> None:
    """Delete legacy QuickNII helper files from older QUINTdeepflow runs."""

    logger = logger or LOG
    patterns = (
        "*_quicknii_preview.jpg",
        "jpgDS_results_quicknii_preview.json",
        "jpgDS_results_quicknii_preview.csv",
        "jpgDS_results_quicknii_preview.xml",
    )
    removed = 0
    for pattern in patterns:
        for path in jpg_dir.glob(pattern):
            if not path.is_file():
                continue
            path.unlink(missing_ok=True)
            removed += 1
    if removed:
        logger.info("Removed %d legacy QuickNII helper file(s)", removed)


def convert_tiffs_to_jpgs(
    tiff_paths: list[Path],
    jpg_dir: Path,
    *,
    logger: logging.Logger | None = None,
) -> list[ConvertedJpg]:
    """Convert TIFF images into 8-bit JPEGs suitable for DeepSlice."""

    logger = logger or LOG
    converted: list[ConvertedJpg] = []
    for path in tiff_paths:
        array = tifffile.imread(str(path))
        jpeg_array, stats = prepare_image_for_deepslice(array)
        output_path = jpg_dir / f"{path.stem}.jpg"
        base_image = Image.fromarray(jpeg_array, mode="L")
        jpeg_quality, file_size_bytes = _save_lightweight_jpeg(
            base_image,
            output_path,
            target_bytes=TARGET_JPEG_BYTES,
            initial_quality=DEFAULT_JPEG_QUALITY,
            min_quality=MIN_JPEG_QUALITY,
        )
        converted_item = ConvertedJpg(
            source_tiff=path,
            output_jpg=output_path,
            enhanced=bool(stats["enhanced"]),
            source_min=float(stats["source_min"]),
            source_max=float(stats["source_max"]),
            source_p99_5=float(stats["source_p99_5"]),
            jpeg_quality=int(jpeg_quality),
            file_size_bytes=int(file_size_bytes),
        )
        converted.append(converted_item)
        logger.info(
            "Prepared %s -> %s (enhanced=%s, p99.5=%.4f, quality=%d, size_mb=%.2f)",
            path.name,
            output_path.name,
            converted_item.enhanced,
            converted_item.source_p99_5,
            converted_item.jpeg_quality,
            converted_item.file_size_bytes / 1_000_000.0,
        )
    return converted


def prepare_image_for_deepslice(image: np.ndarray) -> tuple[np.ndarray, dict[str, float | bool]]:
    """Convert a TIFF-like array into a contrast-balanced 8-bit grayscale image."""

    grayscale = _to_grayscale_float(image)
    positive = grayscale[grayscale > 0]
    if positive.size == 0:
        empty = np.zeros(grayscale.shape, dtype=np.uint8)
        return empty, {
            "enhanced": False,
            "source_min": 0.0,
            "source_max": 0.0,
            "source_p99_5": 0.0,
        }

    source_min = float(np.min(positive))
    source_max = float(np.max(positive))
    source_p99_5 = float(np.percentile(positive, 99.5))
    low = float(np.percentile(positive, 1.0))
    high = max(source_p99_5, low + 1e-6)
    normalized = np.clip((grayscale - low) / (high - low), 0.0, 1.0)

    enhanced = bool(source_p99_5 <= (source_max * 0.32) or np.std(normalized) < 0.09)
    if enhanced:
        normalized = np.power(normalized, 0.75)
        normalized = np.clip((normalized - normalized.min()) / max(normalized.max() - normalized.min(), 1e-6), 0.0, 1.0)
        if exposure is not None:
            normalized = exposure.equalize_adapthist(normalized, clip_limit=0.0125, nbins=256)
            normalized = np.clip(normalized, 0.0, 1.0)
        pil_image = Image.fromarray(np.rint(normalized * 255.0).astype(np.uint8), mode="L")
        pil_image = ImageOps.autocontrast(pil_image, cutoff=1)
        pil_image = pil_image.filter(ImageFilter.MedianFilter(size=3))
        pil_image = pil_image.filter(ImageFilter.UnsharpMask(radius=1.0, percent=110, threshold=2))
        output = np.asarray(pil_image, dtype=np.uint8)
    else:
        pil_image = Image.fromarray(np.rint(normalized * 255.0).astype(np.uint8), mode="L")
        pil_image = ImageOps.autocontrast(pil_image, cutoff=0)
        output = np.asarray(pil_image, dtype=np.uint8)

    return output, {
        "enhanced": enhanced,
        "source_min": source_min,
        "source_max": source_max,
        "source_p99_5": source_p99_5,
    }


def resolve_deepslice_python(explicit: Path | None = None) -> Path:
    """Resolve which Python executable should import DeepSlice."""

    candidates: list[Path] = []
    for env_name in (PRIMARY_DEEPSLICE_ENV_VAR, *LEGACY_DEEPSLICE_ENV_VARS):
        env_value = os.environ.get(env_name, "").strip()
        if env_value:
            candidates.append(Path(env_value))
    if explicit is not None:
        candidates.append(Path(explicit))
    bundle_root = Path(__file__).resolve().parents[2]
    candidates.append(bundle_root / PORTABLE_DEEPSLICE_PYTHON)
    candidates.append(DEFAULT_DEEPSLICE_PYTHON)
    candidates.append(Path(sys.executable))

    for candidate in candidates:
        if not str(candidate).strip():
            continue
        candidate = candidate.resolve()
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        "DeepSlice Python executable was not found. "
        f"Set {PRIMARY_DEEPSLICE_ENV_VAR} or install the DeepSlice environment."
    )


def run_deepslice_predictions(
    *,
    manifest_paths: list[Path],
    output_stem: Path,
    python_executable: Path,
    runner_script: Path,
    species: str,
    use_ensemble: bool,
    same_slicing_angle: bool,
    logger: logging.Logger | None = None,
    manifest_channel: str,
    ap_hint_json_path: Path | None = None,
) -> None:
    """Run the external DeepSlice environment against the prepared JPEG manifest."""

    logger = logger or LOG
    env = build_deepslice_env(python_executable)
    manifest_path = output_stem.parent / f".deepslice_manifest_{manifest_channel.lower()}.json"
    manifest_path.write_text(
        json.dumps([str(path) for path in manifest_paths], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    command = [
        str(python_executable),
        str(runner_script),
        "--manifest",
        str(manifest_path),
        "--output-stem",
        str(output_stem),
        "--species",
        species,
    ]
    if use_ensemble:
        command.append("--ensemble")
    if same_slicing_angle:
        command.append("--same-slicing-angle")
    if ap_hint_json_path is not None:
        command.extend(["--ap-hint-json", str(ap_hint_json_path), "--ap-hint-mode", "hard-clamp"])
    logger.info("Launching DeepSlice: %s", " ".join(command))
    try:
        completed = subprocess.run(
            command,
            cwd=str(runner_script.parent),
            env=env,
            capture_output=True,
            text=True,
            check=False,
        )
    finally:
        manifest_path.unlink(missing_ok=True)
        if ap_hint_json_path is not None:
            ap_hint_json_path.unlink(missing_ok=True)
    if completed.stdout:
        logger.info(completed.stdout.strip())
    if completed.stderr:
        logger.warning(completed.stderr.strip())
    if completed.returncode != 0:
        raise RuntimeError(
            f"DeepSlice failed with exit code {completed.returncode}: {completed.stderr.strip() or completed.stdout.strip()}"
        )


def build_deepslice_env(python_executable: Path) -> dict[str, str]:
    """Build PATH so the external DeepSlice conda environment can load DLLs on Windows."""

    env = os.environ.copy()
    env_root = python_executable.parent
    prefixes = [
        env_root,
        env_root / "Library" / "mingw-w64" / "bin",
        env_root / "Library" / "usr" / "bin",
        env_root / "Library" / "bin",
        env_root / "Scripts",
        env_root / "bin",
        env_root / "DLLs",
    ]
    existing = env.get("PATH", "")
    env["PATH"] = ";".join([str(path) for path in prefixes if path.exists()] + [existing])
    return env


def normalize_prediction_outputs(
    *,
    json_path: Path,
    csv_path: Path,
    xml_path: Path,
) -> None:
    """Rewrite DeepSlice outputs to store JPEG basenames instead of absolute paths."""

    if json_path.exists():
        payload = json.loads(json_path.read_text(encoding="utf-8"))
        payload = sanitize_payload_for_quicknii(payload=payload, default_name=json_path.stem)
        json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    if csv_path.exists():
        frame = pd.read_csv(csv_path)
        if "Filenames" in frame.columns:
            frame["Filenames"] = frame["Filenames"].map(lambda value: Path(str(value)).name)
        frame.to_csv(csv_path, index=False)

    if xml_path.exists():
        text = xml_path.read_text(encoding="utf-8")
        replacements: dict[str, str] = {}
        for chunk in text.split('filename="')[1:]:
            raw = chunk.split('"', 1)[0]
            replacements[raw] = Path(raw).name
        for source, target in replacements.items():
            text = text.replace(f'filename="{source}"', f'filename="{target}"')
        xml_path.write_text(text, encoding="utf-8")


def build_ap_guided_manifest(converted: list[ConvertedJpg], hints: list[DeepSliceApHint]) -> list[Path] | None:
    """Return a hint-sorted JPEG manifest, or None if coverage is incomplete."""

    hint_lookup = build_ap_hint_lookup(hints)
    ordered: list[tuple[float, int, Path]] = []
    for original_index, item in enumerate(converted):
        hint = hint_lookup.get(normalize_slice_lookup_key(item.output_jpg.name))
        if hint is None:
            section_key = extract_section_id(item.output_jpg.name)
            if section_key:
                hint = hint_lookup.get(section_key.lower())
        if hint is None:
            return None
        ordered.append((hint.ap_mm, original_index, item.output_jpg))
    ordered.sort(key=lambda row: (-row[0], row[1]))
    return [path for _, _, path in ordered]


def build_ap_hint_lookup(hints: list[DeepSliceApHint]) -> dict[str, DeepSliceApHint]:
    """Build filename/section lookup table for AP hints."""

    lookup: dict[str, DeepSliceApHint] = {}
    for hint in hints:
        if hint.filename_stem:
            lookup[normalize_slice_lookup_key(hint.filename_stem)] = hint
        if hint.section_id:
            lookup[hint.section_id.lower()] = hint
    return lookup


def write_runner_ap_hint_json(
    *,
    converted: list[ConvertedJpg],
    hints: list[DeepSliceApHint],
    output_path: Path,
) -> Path:
    """Write the compact AP hint JSON consumed inside the DeepSlice runtime."""

    hint_lookup = build_ap_hint_lookup(hints)
    rows: list[dict[str, object]] = []
    for item in converted:
        hint = hint_lookup.get(normalize_slice_lookup_key(item.output_jpg.name))
        section_id = extract_section_id(item.output_jpg.name)
        if hint is None and section_id:
            hint = hint_lookup.get(section_id.lower())
        if hint is None:
            continue
        rows.append(
            {
                "filename": item.output_jpg.name,
                "section_id": section_id,
                "ap_mm": float(hint.ap_mm),
                "tolerance_mm": float(hint.tolerance_mm),
            }
        )
    output_path.write_text(json.dumps({"hints": rows}, ensure_ascii=False, indent=2), encoding="utf-8")
    return output_path


def build_ap_hint_report(
    *,
    json_path: Path,
    hints: list[DeepSliceApHint],
    species: str,
) -> pd.DataFrame:
    """Compare DeepSlice predictions against AP priors."""

    payload = json.loads(json_path.read_text(encoding="utf-8"))
    hint_lookup = build_ap_hint_lookup(hints)
    rows: list[dict[str, object]] = []
    for slice_payload in payload.get("slices", []):
        filename = str(slice_payload.get("filename", ""))
        lookup_key = normalize_slice_lookup_key(filename)
        section_id = extract_section_id(filename)
        hint = hint_lookup.get(lookup_key) or (hint_lookup.get(section_id.lower()) if section_id else None)
        predicted_ap_mm = estimate_slice_ap_mm(slice_payload, species=species)
        row = {
            "filename": filename,
            "section_id": section_id,
            "predicted_ap_mm": predicted_ap_mm,
            "expected_ap_mm": np.nan,
            "tolerance_mm": np.nan,
            "abs_delta_mm": np.nan,
            "outside_tolerance": False,
            "hint_matched": False,
        }
        if hint is not None:
            delta = abs(predicted_ap_mm - hint.ap_mm)
            tolerance = float(hint.tolerance_mm)
            row.update(
                {
                    "expected_ap_mm": hint.ap_mm,
                    "tolerance_mm": tolerance,
                    "abs_delta_mm": delta,
                    "outside_tolerance": bool(delta > (tolerance + 1e-6)),
                    "hint_matched": True,
                }
            )
        rows.append(row)
    return pd.DataFrame(rows)


def rewrite_predictions_to_ap_hints(
    *,
    json_path: Path,
    csv_path: Path,
    xml_path: Path,
    hints: list[DeepSliceApHint],
    species: str,
    logger: logging.Logger | None = None,
) -> pd.DataFrame:
    """Shift AP position and reorder slices to honor the provided AP priors."""

    logger = logger or LOG
    payload = json.loads(json_path.read_text(encoding="utf-8"))
    hint_lookup = build_ap_hint_lookup(hints)
    resolution_vox, voxel_size_um, bregma_x_um = _ap_conversion_parameters(species)

    for slice_payload in payload.get("slices", []):
        filename = str(slice_payload.get("filename", ""))
        section_id = extract_section_id(filename)
        hint = hint_lookup.get(normalize_slice_lookup_key(filename)) or (hint_lookup.get(section_id.lower()) if section_id else None)
        if hint is None:
            continue
        predicted_ap_mm = estimate_slice_ap_mm(slice_payload, species=species)
        delta_mm = hint.ap_mm - predicted_ap_mm
        if abs(delta_mm) <= hint.tolerance_mm:
            continue
        anchoring = np.asarray(slice_payload.get("anchoring", []), dtype=np.float64)
        if anchoring.size < 9:
            continue
        delta_quicknii_y = (delta_mm * 1000.0) / voxel_size_um
        anchoring[1] += delta_quicknii_y
        slice_payload["anchoring"] = [float(value) for value in anchoring.tolist()]
        logger.info(
            "AP rewrite applied to %s: predicted=%.3f mm, target=%.3f mm, shift_quicknii_y=%.3f vox",
            filename,
            predicted_ap_mm,
            hint.ap_mm,
            delta_quicknii_y,
        )

    def sort_key(slice_payload: dict[str, object]) -> tuple[float, int]:
        filename = str(slice_payload.get("filename", ""))
        section_id = extract_section_id(filename)
        hint = hint_lookup.get(normalize_slice_lookup_key(filename)) or (hint_lookup.get(section_id.lower()) if section_id else None)
        order_hint = -hint.ap_mm if hint is not None else -estimate_slice_ap_mm(slice_payload, species=species)
        fallback_nr = int(slice_payload.get("nr", 0) or 0)
        return (order_hint, fallback_nr)

    payload["slices"] = sorted(payload.get("slices", []), key=sort_key)
    for index, slice_payload in enumerate(payload["slices"], start=1):
        slice_payload["nr"] = index

    write_prediction_bundle(
        payload=payload,
        json_path=json_path,
        csv_path=csv_path,
        xml_path=xml_path,
    )
    return build_ap_hint_report(
        json_path=json_path,
        hints=hints,
        species=species,
    )


def estimate_slice_ap_mm(slice_payload: dict[str, object], *, species: str) -> float:
    """Estimate the AP position of a DeepSlice slice from its center point."""

    resolution_vox, voxel_size_um, bregma_x_um = _ap_conversion_parameters(species)
    width = float(slice_payload.get("width", 0) or 0)
    height = float(slice_payload.get("height", 0) or 0)
    anchoring = np.asarray(slice_payload.get("anchoring", []), dtype=np.float64)
    if anchoring.size < 9:
        raise ValueError(f"Slice {slice_payload.get('filename')!r} does not contain a 9-value anchoring array.")
    origin = anchoring[0:3]
    u = anchoring[3:6]
    v = anchoring[6:9]
    center_point = origin + (u * 0.5) + (v * 0.5)
    point_y = float(center_point[1])
    allen_x_um = (float(resolution_vox[1] - 1) - point_y) * voxel_size_um
    ap_um = bregma_x_um - allen_x_um
    return ap_um / 1000.0


def write_prediction_bundle(
    *,
    payload: dict[str, object],
    json_path: Path,
    csv_path: Path,
    xml_path: Path,
) -> None:
    """Write synchronized JSON / CSV / XML DeepSlice outputs from one payload."""

    payload = sanitize_payload_for_quicknii(payload=payload, default_name=json_path.stem)
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    rows: list[dict[str, object]] = []
    for slice_payload in payload.get("slices", []):
        anchoring = list(slice_payload.get("anchoring", []))
        while len(anchoring) < 9:
            anchoring.append(0.0)
        rows.append(
            {
                "Filenames": slice_payload.get("filename", ""),
                "ox": anchoring[0],
                "oy": anchoring[1],
                "oz": anchoring[2],
                "ux": anchoring[3],
                "uy": anchoring[4],
                "uz": anchoring[5],
                "vx": anchoring[6],
                "vy": anchoring[7],
                "vz": anchoring[8],
                "width": slice_payload.get("width", 0),
                "height": slice_payload.get("height", 0),
            }
        )
    pd.DataFrame(rows).to_csv(csv_path, index=False)

    if xml_path.exists():
        tree = ET.parse(xml_path)
        root = tree.getroot()
    else:
        root = ET.Element("series")
        tree = ET.ElementTree(root)
    for child in list(root):
        root.remove(child)
    root.attrib["first"] = "1"
    root.attrib["last"] = str(len(payload.get("slices", [])))
    root.attrib["name"] = str(json_path.with_suffix(""))
    if payload.get("aligner") is not None:
        root.attrib["aligner"] = str(payload.get("aligner"))
    for slice_payload in payload.get("slices", []):
        anchoring = list(slice_payload.get("anchoring", []))
        while len(anchoring) < 9:
            anchoring.append(0.0)
        anchor_text = (
            f"ox={anchoring[0]}&oy={anchoring[1]}&oz={anchoring[2]}"
            f"&ux={anchoring[3]}&uy={anchoring[4]}&uz={anchoring[5]}"
            f"&vx={anchoring[6]}&vy={anchoring[7]}&vz={anchoring[8]}"
        )
        element = ET.SubElement(root, "slice")
        element.set("anchoring", anchor_text)
        element.set("filename", str(slice_payload.get("filename", "")))
        element.set("height", str(int(slice_payload.get("height", 0) or 0)))
        element.set("width", str(int(slice_payload.get("width", 0) or 0)))
        element.set("nr", str(int(slice_payload.get("nr", 0) or 0)))
    tree.write(xml_path, encoding="utf-8", xml_declaration=True)


def sanitize_payload_for_quicknii(*, payload: dict[str, object], default_name: str) -> dict[str, object]:
    """Reduce DeepSlice output to the minimal JSON schema QuickNII expects."""

    raw_resolution = payload.get("target-resolution", [456, 528, 320])
    if isinstance(raw_resolution, tuple):
        raw_resolution = list(raw_resolution)
    if not isinstance(raw_resolution, list):
        raw_resolution = [456, 528, 320]
    target_resolution = [int(round(float(value))) for value in raw_resolution[:3]]
    while len(target_resolution) < 3:
        target_resolution.append((456, 528, 320)[len(target_resolution)])

    sanitized_slices: list[dict[str, object]] = []
    raw_slices = payload.get("slices", [])
    if isinstance(raw_slices, list):
        for index, slice_payload in enumerate(raw_slices, start=1):
            if not isinstance(slice_payload, dict):
                continue
            anchoring_raw = slice_payload.get("anchoring", [])
            anchoring_values: list[float] = []
            if isinstance(anchoring_raw, list):
                anchoring_values = [float(value) for value in anchoring_raw[:9]]
            while len(anchoring_values) < 9:
                anchoring_values.append(0.0)
            sanitized_slice: dict[str, object] = {
                "filename": Path(str(slice_payload.get("filename", ""))).name,
                "nr": int(slice_payload.get("nr", index) or index),
                "width": int(slice_payload.get("width", 0) or 0),
                "height": int(slice_payload.get("height", 0) or 0),
            }
            if any(value != 0.0 for value in anchoring_values):
                sanitized_slice["anchoring"] = anchoring_values
            markers_raw = slice_payload.get("markers", [])
            if isinstance(markers_raw, list):
                markers: list[list[float]] = []
                for marker in markers_raw:
                    if isinstance(marker, list) and len(marker) >= 4:
                        try:
                            markers.append([float(value) for value in marker[:4]])
                        except (TypeError, ValueError):
                            continue
                if markers:
                    sanitized_slice["markers"] = markers
            sanitized_slices.append(sanitized_slice)

    return {
        "name": str(payload.get("name", "") or default_name),
        "target": str(payload.get("target", "") or "ABA_Mouse_CCFv3_2017_25um.cutlas"),
        "target-resolution": target_resolution,
        "slices": sanitized_slices,
    }


def normalize_slice_lookup_key(value: str) -> str:
    """Normalize filenames and stems for AP-hint matching."""

    return Path(str(value).strip()).stem.lower()


def extract_section_id(value: str) -> str | None:
    """Extract XY-like section id from a filename."""

    match = SECTION_ID_PATTERN.search(str(value))
    return match.group(1).upper() if match else None


def _ap_conversion_parameters(species: str) -> tuple[tuple[int, int, int], float, float]:
    if species.lower() != "mouse":
        raise ValueError("AP hint conversion is currently implemented for mouse DeepSlice outputs only.")
    return DEEPSLICE_MOUSE_QUICKNII_RESOLUTION, DEEPSLICE_MOUSE_VOXEL_SIZE_UM, DEEPSLICE_MOUSE_BREGMA_UM[0]


def _to_grayscale_float(image: np.ndarray) -> np.ndarray:
    """Convert a TIFF-like array to 2D float grayscale."""

    array = np.asarray(image)
    if array.ndim == 2:
        return array.astype(np.float32, copy=False)
    if array.ndim == 3 and array.shape[-1] in {3, 4}:
        rgb = array[..., :3].astype(np.float32, copy=False)
        return (0.299 * rgb[..., 0]) + (0.587 * rgb[..., 1]) + (0.114 * rgb[..., 2])
    if array.ndim == 3:
        return np.mean(array.astype(np.float32, copy=False), axis=0)
    raise ValueError(f"Unsupported TIFF shape: {array.shape}")


def _save_lightweight_jpeg(
    image: Image.Image,
    output_path: Path,
    *,
    target_bytes: int,
    initial_quality: int,
    min_quality: int,
) -> tuple[int, int]:
    """Save a same-dimension JPEG while iteratively reducing file size."""

    quality_steps = []
    current = int(initial_quality)
    while current >= int(min_quality):
        quality_steps.append(current)
        if current <= int(min_quality):
            break
        current = max(int(min_quality), current - 6)
        if quality_steps and current == quality_steps[-1]:
            break

    best_payload: bytes | None = None
    best_quality = int(min_quality)
    for quality in quality_steps:
        buffer = io.BytesIO()
        image.save(
            buffer,
            format="JPEG",
            quality=int(quality),
            optimize=True,
            progressive=True,
        )
        payload = buffer.getvalue()
        best_payload = payload
        best_quality = int(quality)
        if len(payload) <= int(target_bytes):
            break

    assert best_payload is not None
    output_path.write_bytes(best_payload)
    return best_quality, len(best_payload)
